-- export (6) v2 chunk 016 — 4 updates

-- id=42792 source=page_meta | Essays on Vertical Contracting
UPDATE papers SET authors = 'Zhang, Zilong', snippet = 'This thesis studies the effect of financial contracting on two major corporate activities - trade credit finance and mergers and acquisitions. Chapter 1 examines when a borrowing firm violates loan covenant, how bank interventions in this borrower affect the borrower&amp;amp;#039;s trade credit. Trade credit declines when banks obtain additional control rights following debt covenant violations. Interventions that are likely to result in acceleration of loan repayments lead to larger reductions in trade credit. In addition, dependent suppliers that have made customer-specific investments are adversely affected by bank interventions. Ex ante, firms take into account the effect of bank control on dependent suppliers and accordingly offer less restrictive debt contracts. These results suggest that debt covenant violations have large negative externalities for dependent suppliers and firms take these externalities into account when designing loan contracts. In Chapter 2, we find that differences in the compensation of acquirer and target firms&amp;amp;#039; management teams negatively affect the outcomes of mergers. Larger differences in top management pay are associated with lower returns to the acquiring firm after the announcement of the merger and negative combined wealth effects. Larger pay differences also increase the likelihood of employee layoffs. Overall, our results suggest that differences in executive compensation are indicators of integration problems at merging firms, which in turn negatively affect merger outcomes.' WHERE id = 42792;

-- id=42757 source=semantic_scholar_title | Exploring the Impact of Large Language Model-Simulated Personalities on Recommendation
UPDATE papers SET authors = 'Zining Feng, Zijing Wang, Hongzan Mao, Baisong Liu', snippet = 'In recent years, Large Language Model-based Recommendation Systems (LLMRec) have achieved remarkable advancements. By designing effective prompts, LLMs can understand user interests and either directly generate recommendations based on users'' interests or assist traditional recommendation systems in enhancing recommendation performance. However, existing LLMRec predominantly leverage LLMs as static tools for user interest understanding, ignoring the dynamic behavioral patterns of LLMs when simulating human personalities. While some studies explore LLMs'' human-like behaviors in conversational scenarios, their impacts on recommendation systems remain underexplored. To fill these gaps, this paper aims to investigate how LLM-simulated personalities interact with users of varying personalities in recommendation systems, particularly focusing on whether LLM-simulated personalities exhibit behaviors align with Social Homophily Theory which is well-documented in human social interactions but unexplored in LLMRec. We conducted experiments on two public datasets, inducing LLMs to simulate different human personalities based on the Big Five Personality Traits through prompt engineering, and incorporating the generated user profiles into the Knowledge Augmented Recommendation framework to evaluate performance across various recommendation models. Experimental results demonstrate that inducing LLMs to simulate personality in the KAR framework significantly influences recommendation performance. Moreover, LLM-simulated personalities exhibit a preference for users with similar personalities, mirroring the Social Homophily Theory observed in human behavior.' WHERE id = 42757;

-- id=42746 source=semantic_scholar_title | Personality traits and early maladaptive schemas in methadone maintenance patients vs. hea
UPDATE papers SET authors = 'Azam Kargar, A. Ganjali', snippet = 'This research investigated the differences in personality traits and early maladaptive schemas between patients undergoing methadone maintenance treatment and healthy controls in Zahedan, Iran. The study involved 81 patients in methadone maintenance treatment and 81 healthy controls, assessing them using the Big Five Inventory - Short Version and the Young Schema Questionnaire 90-item. Data analysis using independent t-tests and Chi-square tests in SPSS v25 revealed significant differences in both personality traits and early maladaptive schemas between the study groups. The methadone group was more extroverted and neurotic, with no differences in openness to experience, conscientiousness, or agreeableness. They scored significantly higher in early maladaptive schemas (395.4±36.5) than the control group (317.9±32.8), indicating a higher likelihood of maladaptive schemas. Significant differences were found in specific schemas, such as “abandonment/instability”, “social isolation”, “negativity/pessimism”, “defectiveness/shame”, “mistrust/abuse”, “insufficient self-control”, “enmeshment”, and “failure to achieve”, with the methadone maintenance group exhibiting more maladaptive schemas. The findings highlight the importance of incorporating personality traits and early maladaptive schemas in therapy for substance users to enhance treatment outcomes.' WHERE id = 42746;

-- id=42724 source=page_meta | Light Triad traits of personality as moderators between the dark core of personality, psyc
UPDATE papers SET authors = 'Pedro Pechorro, Victor H Palma, João Maroco, Mário R Simões, Matt DeLisi', snippet = 'The current study aims at examining the potential role of Light Triad traits of personality as moderators of the dark core of personality–psychopathy–antisociality/criminality links. A convenience sample composed of 354 adult participants ...' WHERE id = 42724;

