-- export (6) v2 chunk 015 — 32 updates

-- id=43648 source=openalex_title | When sustainability speaks louder: the role of ESG in mitigating the impact of manager per
UPDATE papers SET authors = 'Renata Pesente, Kachirí Vitória Noara Farias, Cristian Baú Dal Magro, Larissa de Lima Trindade, Maurício Leite', snippet = 'Purpose: To analyze the moderating effect of ESG practices on the relationship between manager personality traits and earnings management practices in credit cooperatives. Methodology: The study involved 83 credit cooperative managers with data collected through an online survey. Descriptive statistics and multiple linear regression techniques were applied for analysis using Stata® software. Results: The findings indicate that manager personality traits significantly influence the adoption of earnings management practices. However, the implementation of ESG practices demonstrated a positive moderating effect, discouraging managers with Dark Triad traits (Machiavellianism, narcissism, and psychopathy) from engaging in opportunistic behaviors. Contributions of the Study: This study contributes to the literature by integrating behavioral and organizational aspects, highlighting how psychological traits influence opportunistic practices and how ESG practices can mitigate these effects. From a practical perspective, the results suggest that credit cooperatives can reduce manipulative practices by adopting robust ESG policies. Additionally, incorporating personality trait analysis into the recruitment and selection process can help identify candidates aligned with organizational values and less prone to earnings manipulation. This can enhance transparency, strengthen corporate governance, and build stakeholder trust.' WHERE id = 43648;

-- id=43649 source=openalex_title | The impacts of achievement goal orientation, dark triad, person-environment misfit, and pe
UPDATE papers SET authors = 'Changxian Yi, Haifeng Zhang', snippet = 'Many organizations are unable to leverage the benefits of external hires due to the latter''s deviant behaviors. Drawing on person-environment fit and trait activation theories alongside goal orientation and dark triad personality research, we hypothesized and tested a conceptual model elucidating the mechanisms underlying deviant behaviors in this unique context. Our study, based on data from 236 external hires and their supervisors, reveals that these hires exhibit deviant behaviors when they experience a misalignment between their personal traits and the organizational environment. In particular, achievement goal orientation and dark triad traits (narcissism, Machiavellianism, psychopathy), often developed in highly competitive settings, predispose external hires to perceive poor alignment (i.e., a lack of person-environment fit) between their needs and the resources or demands of their new roles. Furthermore, perceived psychological safety in the workplace buffers the negative impact of these traits on misfit perceptions, thereby reducing the likelihood of deviant behaviors. Our findings suggest that tailored onboarding programs, a psychologically safe climate, and the promotion of open communication are essential for successfully integrating external hires and minimizing their deviant behaviors.' WHERE id = 43649;

-- id=43651 source=page_meta | To vaccinate or not to vaccinate? Dark triad personality traits in the context of decision
UPDATE papers SET authors = 'Badura-Brzoza, Karina, Główczyński, Patryk, Dębski, Paweł, Brzoza, Zenon', snippet = 'IntroductionThe COVID-19 pandemic and the related restrictions have changed the lives of people around the world. Compliance with the recommendations issued by the WHO and the ministries of health of individual countries was important in order to limit the transmission of the SARS-COV-2 virus. Over time, public vaccinations against COVID-19 appeared, which gave rise to a wave of anti-vaccine demonstrations.Aim of the studyBearing in mind the hypothesis about the relationship between the characteristics of the Dark Triad and pro-health behaviors, The aim of the study was to analyze the possible correlations between Dark Triad personality traits, the levels of anxiety and depressive symptoms and vaccination behavior.Material419 people participated in the study, including 317 people aged 35.87 ± 13.65 SD years who received the Covid-19 vaccination and 102 people aged 38.18 ± 12.13 SD years who decided not to receive the vaccine.MethodsThe Dirty Dozen Scale (DDS), the Perceived Stress Scale (PSS-10) and the State and Trait Anxiety Inventory (STAI-X2) were used in the study.ResultsOn the Dirty Dozen Scale, the vaccinated group had an average score of 23.29 ± 10.10 SD and the unvaccinated group had an average score of 20.81 ± 8.84 SD. Comparative analysis of the study groups showed statistically significant differences both in the overall DDS score and in its subscales - machiavellianism and narcissism. There were no differences in the psychopathy subscale. When analyzing the relationship between anxiety as a trait and stress assessed with the PSS-10 scale, no statistically significant correlations were found in the overall score on the DDS scale, as well as in the subscales of machiavellianism, psychopathy and narcissism.ConclusionsIn the study, people with features of machiavellianism and narcissism more often decided to vaccinate against COVID-19, such a relationship could not be established for people with features of psychopathy. Aversive personality traits that…' WHERE id = 43651;

-- id=43652 source=openalex_doi | Balancing the Edge: Dark Traits, Neuroticism, and Entrepreneurship Success
UPDATE papers SET authors = 'Oleg V. Petrenko, Thomas H. Allison, Paul Sanchez Ruiz, Blakley C. Davis, Benjamin J. Warnick, Katrina M. Brownell, Amrit Panda, Andrew B. Blake', snippet = 'This symposium examines the role of personality traits, including the Dark Triad and neuroticism, in shaping entrepreneurial processes and outcomes. The studies explore their impact on innovation, venture growth, industry selection, and funding success, highlighting the nuanced interplay between these traits and contextual factors like self- efficacy and gender. Drawing on theories from personality psychology and social cognition, the symposium challenges traditional views, showcasing how these traits can serve as assets in entrepreneurship under the right conditions, with valuable implications for research and practice. The Good, The Bad, and The Ugly: Founder-CEOs’ Dark Triad Traits, TMT Conflict, and Innovation Author: Andreas Rauch; Audencia Business School Author: Asghar Jahanshahi; Author: Wenping Ye; Jinan University Author: Xue Wan; University of Leeds Dark Traits and Bright Outcomes: The Contingent Role of Self-Efficacy and Gender in Venture Growth Author: Keith Hmieleski; Texas Christian University Breaking Barriers, Building Ventures: The Effects of Status and Narcissism on Industry Selection Author: Mahija Ratnoo; Texas Tech University Harnessing Vulnerability: The Positive Effects of Neuroticism on Entrepreneurial Funding Success Author: Johnny Blaine Smith; University of Arkansas Author: Diana Maria Hechavarria; Babson College Author: Sean Lux; Texas Tech University Author: G Tyge Payne; Not Associated Author: Nathan Hayes; Louisiana State University' WHERE id = 43652;

-- id=43655 source=openalex_title | The dual nature of arrogance: from an approach-avoidance perspective
UPDATE papers SET authors = 'Yinghua Xu, Heming Gong', snippet = 'Abstract Arrogance is common and aversive in social interactions, yet its psychological structure has received limited attention. In this research, we propose two domains of arrogance—approach-oriented and avoidance-oriented—and provide support for the theoretical distinction between these two domains through two studies. In Study 1, we establish an initial scale through content validity and identify eight first-order arrogance factors through exploratory factor analysis. In Study 2, we develop two categories of arrogant expressions and further refine the scale into a higher-order construct based on these expressions. Moreover, we compare the correlations between two domains of arrogance, personality traits, and social interactions to gain a better understanding of the arrogance construct. Specifically, approach-oriented arrogance is more positively related to extraversion and dark triad traits, more negatively related to agreeableness, and elicits more unfavorable social interactions such as being more disliked, receiving less communication, as well as more negative evaluations of intelligence from others when compared to avoidance-oriented arrogance. These findings can help future researchers and practitioners assess arrogance domains, and mitigate the negative effects of arrogance.' WHERE id = 43655;

-- id=43657 source=openalex_title | Exploring the dark triad and sexting practices in Portuguese young adults
UPDATE papers SET authors = 'Mariana Costa, Claúdia Gouveia, Sónia Caridade', snippet = 'Abstract In order to maintain intimate relationships and explore their own sexuality, young adults commonly use Information and Communication Technologies (ICT) for Online Sexual Activities (OSA). OSA activities like sexting have increased significantly with the widespread adoption of ICT, exposing young people to heightened risks of online violence. This study aims to validate and examine the psychometric properties of the Sexting Scale for the Portuguese population, describe the prevalence of sexting among young adults in Portugal, and investigate possible correlations with personality traits. The sample included 329 participants ( M age = 20.83; SD = 1.992). The Exploratory Factor Analysis (EFA) and Confirmatory Factor Analysis (CFA) demonstrated very acceptable values, supporting a three-factor model of sexting: erotic, pornographic, and romantic. Among the participants, 94.8% of women and 85.5% of men reported engaging in at least one act of sexting. Sexting experience showed a strong and positive association with higher levels of machiavellianism and narcissism. However, no significant association was found between sexting and high levels of psychopathy. These findings underscore the importance of addressing non-consensual sexting as a critical health and social issue, emphasizing the need for interventions aimed at preventing and managing this form of abuse.' WHERE id = 43657;

-- id=43662 source=openalex_doi | Hidden Benefits of Dark Personality Traits in Driving Sustainable Workplace Behaviors
UPDATE papers SET authors = 'Isotília Costa Melo, Jeanne Le Roy, Sarah Hoenigsberg, Hendrik Wache, Jéssica Syrio Callefi', snippet = 'The study examines how employees’ personality traits of the Dark Triad (narcissism, psychopathy, and Machiavellianism) can positively influence workplace sustainability through Sustainable Positive Deviance (SPD). Analyzing 690 responses in two studies, findings reveal these traits can foster societal and sustainability-oriented behaviors (SB and SOB) driving SPD. Organizational green culture impacts SB and SOB but not SPD. Results suggest that promoting SB as a precursor to sustainability and recognizing unconventional ethical actions can enhance organizational innovation. Surprisingly, traits typically viewed as unfavorable can contribute positively. Practical recommendations include fostering cultures valuing ethical deviance and leadership autonomy to achieve sustainability goals and innovation. Further research is needed.' WHERE id = 43662;

-- id=43663 source=page_meta | Exploring Heavy Work Investment: Multidimensional Constructs and Work
UPDATE papers SET authors = 'Vandenberghe, Christian, Tziner, Aharon, Acosta-Prado, Julio César  César', snippet = 'studies (71,625 participants) across 23 countries. With an overall pooled prevalence of 15.2%, the analysis reveals that roughly one in seven employees may be affected by workaholism. Metaregression showed that studies using nationally representative samples reported significantly lower prevalence (around 9.8%), while non-representative samples yielded higher estimates. Triad personality traits (narcissism, Machiavellianism, and psychopathy) interacted with career interests to predict subjective and objective career success among 300 South African professionals. They found that the association between narcissism and higher career success is amplified for individuals with enterprising interests, while Machiavellianism was linked to better success when social interests were high. In contrast, psychopathy showed limited predictive value for career outcomes regardless of interest type. The study situates its findings within personenvironment fit theory, highlighting that Dark Triad traits can be leveraged adaptively depending on one&#39;s vocational interests. The authors acknowledge limitations to their study, including crosssectional design and self-report measures, and call for longitudinal and multi-method approaches to clarify causal pathways.' WHERE id = 43663;

-- id=43664 source=openalex_doi | Validation of an efficacy of lying scale
UPDATE papers SET authors = 'Christopher J. Carpenter, Kim B. Serota, Tony Docan-Morgan, Timothy R. Levine', snippet = 'Efficacy of lying is the belief that lying is an effective and efficient communication strategy. A new measure of efficacy of lying is presented to assess the belief that lying is an effective way to influence the behavior and beliefs of others. The current study (N = 632) found evidence that the measure is associated with the frequency of lying, self-reported lying ability, and personality traits associated with lying (low honesty and Machiavellianism). The measure’s value was also demonstrated as a moderator of the relationship between general persuasive ability and the use of deception. The data were consistent with the construct validity of the measure and its usefulness in exploring deceptive message production.' WHERE id = 43664;

-- id=43665 source=openalex_title | When Darkness Meets Pressure: The Impact of Dark Triad Personality Traits on Work Stress a
UPDATE papers SET authors = 'Yuniar Hasana, Siti Nuzulia', snippet = 'Work stress is a prevalent issue across organizational settings, yet its relationship with dark personality traits remains underexplored in collectivistic culture contexts. This study investigates the impact of narcissism, Machiavellianism, and psychopathy on work-related stress among employees in Indonesia. This study employed a quantitative methodology and a cross-sectional design, with 255 employees in Indonesia selected via quota sampling. Data analysis was conducted using the General Linear Model (GLM). The findings indicate that psychopathy positively affects work stress, while Machiavellianism negatively impacts work stress. Narcissism does not have a significant effect on work stress. Marital status influences stress levels, with unmarried employees showing greater vulnerability to stress than those who are married. These results suggest that both Dark Triad personality traits and certain demographic factors contribute to variations in work stress. The study highlights the importance of considering personality and demographic characteristics in recruitment and employee support initiatives. Tailoring stress management strategies to individual profiles may enhance employee well-being and promote greater organizational effectiveness.' WHERE id = 43665;

-- id=43668 source=openalex_doi | Leader/Group Congruence in Dark Triad: Effects on Positive Affect and Innovation
UPDATE papers SET authors = 'Mickey B. Smith, I‐Heng Wu, Brian D. Webster', snippet = 'Prior research has demonstrated the complex effects of congruence between leaders and followers. Additionally, dark personality traits, such as those in the Dark Triad, play a critical role in shaping the social and performance cultures in the workplace. The current poster integrates the research on congruence and dark personality to cast a light on how congruence of dark traits, at moderate levels, may lead to beneficial outcomes within groups. We test our model using multi-source data from 41 workgroups. Results support our hypothesized effect between congruence and positive affect, which subsequently is associated with group innovation.' WHERE id = 43668;

-- id=43671 source=openalex_title | The Intersection of Giftedness, Disability, and Cultural Identity: A Case Study of a Young
UPDATE papers SET authors = 'Tammy Jean Byrd, Ty’Bresha Ebony Glass, Ophélie Allyssa Desmet, F. Richard Olenchak', snippet = 'The present research examines the intersections of giftedness, disability status, and cultural identity through the case of Kent, a nine-year-old Asian American boy who is not only profoundly gifted but has also been diagnosed with autism spectrum disorder (ASD), attention deficit hyperactivity disorder (ADHD), and possibly developmental coordination disorder (DCD). This study offers a comprehensive exploration of how these overlapping factors shape Kent''s early talent development and educational experiences, while also highlighting the challenges faced by his family and their need for a personalized, holistic support system tailored to his unique combination of abilities and disabilities. While Kent''s case is not generalizable, it underscores the critical importance of understanding the dynamic interplay among giftedness, disability status, and cultural identity in developing effective educational strategies. Furthermore, we advocate for personalized interventions that extend beyond conventional approaches, such as applied behavior analysis (ABA), to adequately address the complex needs of multi-exceptional individuals like Kent.' WHERE id = 43671;

-- id=43672 source=openalex_title | Online gaming as a criminological environment: exploring criminogenic needs and offending 
UPDATE papers SET authors = 'L. M. J. Bekkers, Thomas J. Holt, Rutger Leukfeldt', snippet = 'Purpose The purpose of this study is to better understand the associations between online gaming and cybercrime. More specifically, the authors explore the individual risks of gamers and the role of gaming in various forms of criminal behaviors. Currently, research is unclear and inconsistent about the possible criminogenic function of online gaming. Design/methodology/approach This cross-sectional study uses a sample of 1,240 Dutch young people aged between 16 and 25 years. Respondents completed a survey consisting of previously validated measurements, screening for criminal behaviors and key criminogenic needs. A number of regression models were estimated to explore the specific factors and crimes associated with gaming, differentiating young people based on the hours they spent on online gaming per week. Findings Analysis revealed that gaming was negatively associated with most criminal behaviors, which indicates a protective function. Risks were primarily observed for in-game deviance, such as theft from opponents. However, gamers showed higher levels of technological skills, were more disinhibited online and were also more likely to be exposed to online deviant peer support compared to non-gamers. These factors can potentially facilitate escalation in cybercrime offending for a subset of young people under specific circumstances. Originality/value This study is one of the first to address the criminogenic needs and offending behaviors associated with various levels of online gaming. Future research could explore more in-depth the role of gaming together with peers as opposed to gaming alone.' WHERE id = 43672;

-- id=43677 source=openalex_title | Building a Resilient Organization Through Informal Networks: Examining the Role of Individ
UPDATE papers SET authors = 'Jin Xiao-yan, Daegyu Yang, Wanlan Sun, Lian Xu', snippet = 'Modern organizations operate not only through formal structures but also through informal networks, which play a critical role in fostering a resilient organization. This study focused on informal advice networks within organizations as a key mechanism for strengthening contextual resilience, one of the core components of organizational resilience. By analyzing the activation of informal advice networks, this study conceptualized advice-seeking networks as a critical informal system that enhances contextual resilience and examined the individual, structural, and attitudinal factors influencing their formation. Specifically, we hypothesized that employees with higher levels of Machiavellianism are more likely to engage in advice-seeking behaviors, whereas the relationship between Machiavellianism and advice-seeking behaviors is moderated by betweenness centrality and organizational commitment, such that the positive effect of Machiavellianism on advice-seeking is weaker when betweenness centrality or organizational commitment is high. To empirically test these hypotheses, we conducted a network survey of employees at the headquarters of a life insurance company in Seoul, South Korea, and analyzed the data using an Exponential Random Graph Model (ERGM). The findings provide empirical support for all hypotheses. Based on these results, we discussed the theoretical contributions and practical implications of the study, along with its limitations.' WHERE id = 43677;

-- id=43678 source=openalex_title | Evaluating AI Use and its Psychological Correlates via Months of Web-Browsing Data
UPDATE papers SET authors = 'Emily K McKinley, David M. Markowitz, Rui Zhu, Brandon Van Der Heide', snippet = 'Despite widespread discussions about Artificial Intelligence (AI) and its impact on society, little work has objectively measured how often people use this technology in the wild. The present paper collected up to 90 days of web-browsing data from students (Study 1: N = 499) and those in the general public (Study 2: N = 455), quantifying how often people used AI and evaluating the psychological correlates of such use. Upon coding 4.1 million websites in Study 1 and 9.9 million websites in Study 2, the evidence suggested AI use was relatively infrequent, totaling 1% of student web-browsing and 0.44% of general public web browsing, on average. The most consistent predictors of AI use across studies were aversive personality traits (e.g., Machiavellianism, narcissism, psychopathy), albeit the traits were differentially associated with AI use across studies. Demographics were systematically unrelated to AI use across studies. Finally, we observed that self-reported AI use and actual AI use were only moderately correlated (ρ = .329), suggesting limitations in subjective measures of media use. These findings provide some of the first behavioral measurements of AI in naturalistic settings and establish important benchmarks for understanding the individual differences associated with AI adoption.' WHERE id = 43678;

-- id=43680 source=openalex_title | Construction and preliminary validation of a Psychopathic Boldness Scale in college and on
UPDATE papers SET authors = 'David K. Marcus, Alexa M. Lambros, Madeline G. Nagel, Montana L. Ploe, Keira L Monaghan, Brian F. French', snippet = '= 125, 55% White) were used to select items and examine the factor structure, internal consistency reliability, item functioning, and convergent and discriminant validity of this scale. The PBS had a three-factor (higher order) structure in which the three factors (fearlessness, social potency, carefree rule breaking) were highly intercorrelated, justifying the use of a total score. The PBS was internally consistent, and all 21 items functioned well. The PBS was positively correlated with measures of boldness, meanness, and disinhibition. The PBS was positively associated with antisocial behavior, Machiavellianism, sensation seeking, fearlessness, and behavioral activation. It was negatively associated with agreeableness, conscientiousness, honesty-humility, altruism, and behavioral inhibition. Although additional research with diverse samples and biobehavioral correlates of boldness is needed, the PBS appears to be a promising measure that may address some of the criticisms of boldness as a component of psychopathy. (PsycInfo Database Record (c) 2025 APA, all rights reserved).' WHERE id = 43680;

-- id=43682 source=openalex_title | The role of expertise, personality traits and decision-making styles in criminal case eval
UPDATE papers SET authors = 'Letizia Caso, Giorgia Pergolizzi, Dalila Vitali, Nicola Palena', snippet = 'Purpose The decision-making process represents the optimal mechanism for evaluating criminal acts. Consequently, it is essential to ascertain whether external factors may potentially influence the evaluation process. The purpose of this study is to identify the factors that are most likely to influence the decision-making process, with a particular focus on the role of personality styles in shaping perceptions of punishment and the outrageousness of criminal acts. Design/methodology/approach This research project focused on the assessment of two distinct types of (mock) criminal acts: domestic violence and an act of negligence perpetrated by a pharmaceutical company. The crime assessment was conducted by three distinct groups, differentiated according to their level of expertise: law students, students from other professions and judges. Additionally, it explored the potential influence of an individual’s personality or decision-making style on the evaluation of criminal acts. The objective of this study is to identify the factors that are most likely to influence the decision-making process, with a particular focus on the role of personality styles in shaping perceptions of punishment and the outrageousness of criminal acts. Findings The results of this study demonstrated that there are disparate evaluations of crime contingent on the group to which one belongs. The personality trait that exhibited the most robust correlation was Machiavellianism. Indeed, as this tendency became more prevalent, so did the assignment of punishment and the perceived outrageousness of the offense. No correlation was found between a more intuitive or more reflective decision-making style. In conclusion, it can be stated that, when all the factors analysed are taken into account, the decision-making process is subject to influences. Research limitations/implications The limited number of judges (n = 18) reduces the generalizability of findings on expertise effects. While including real…' WHERE id = 43682;

-- id=43684 source=openalex_doi | Republic of Iraq
UPDATE papers SET authors = 'World Bank', snippet = 'This report - the first phase of a programmatic Iraq country economic memorandum (CEM) is structured around the themes of revenue management and economic diversification. These themes accord with the economic challenges faced by Iraq in the medium term but contrast with the short-termism of current Iraqi decision making, which is pushing for a rapid ramp-up of oil production - reducing diversification to finance a large up-front spending program which is detached from a vision of how to diversify the economy. Iraq''s oil revenue boom will not be able to meet the expectations placed upon it without a range of supporting policies. Iraq should aim towards adapting its economy to strong weight of oil, as opposed to complete insulation of the non-oil economy from it or dependence on it. To address the myriad links between Iraq''s economic challenges, the report takes a sequential approach to the analysis. Chapter one presents an overview of the fiscal aspects of prospective developments in the energy sector, and an outline of major obstacles to growth in the non-oil economy. Chapter two, a relatively high-level and abstract economic model is developed to study the impact of various options for spending the oil revenue windfall on the non-oil economy. Chapter three, the opportunities for the development of the non-oil economy are set out in more detail along with recommended next steps in the World Bank support to the government of Iraq.' WHERE id = 43684;

-- id=43685 source=semantic_scholar_title | New approach to assessing the manipulative impact of artificial intelligence on public con
UPDATE papers SET authors = 'I. D. Grachev, Sergei N. Larin, N. V. Noakk, T.A. Kostina', snippet = 'Subject. The article addresses the impact of artificial intelligence on the consciousness of individual and society as a whole. Objectives. The focus is on minimizing the risks of negative impact of artificial intelligence algorithms on civilizational values of the Russian society in the light of the current geopolitical situation. Methods. The study employs system tools, that open up opportunities for making adequate situational management decisions. To summarize the findings, we used well-known tests and standard methods for evaluating their results. Results. The paper presents the results of our experimental study on the issue of bias in assessments influenced by the manipulativeness of artificial intelligence algorithms. The results demonstrate that for the "individualism-collectivism" factor, there is no bias in assessments influenced by the manipulativeness of artificial intelligence algorithms, with a compression of variability that is indisputable for any accepted levels of significance. As for the "machiavellianism" factor, which characterizes the degree of manipulativeness, the bias in assessments generated by artificial intelligence for groups of conditional "personalities" significantly differs from the corresponding indicators of control groups of individuals. Conclusions. Further research on the manipulative impact of artificial intelligence algorithms on public consciousness regarding the factor of "Machiavellianism" is advisable.' WHERE id = 43685;

-- id=43687 source=openalex_title | How Collaboration Context and Personality Traits Shape the Social Norms of Human-to-Avatar
UPDATE papers SET authors = 'Seoyoung Kang, Boram Yoon, Kangsoo Kim, Jonathan Gratch, Woontack Woo', snippet = 'As avatars have evolved from simple digital representations into extensions of our identities, they offer unprecedented opportunities for self-expression and customization beyond the physical world limitations. While virtual platforms foster new forms of identity exploration, social norms still play a crucial role in defining what is considered appropriate in these environments. In this study, we surveyed 150 participants to investigate social norms surrounding avatar modifications, examining how perspectives, contexts, and personality traits influence attitudes toward appropriateness. Our findings reveal that avatar modifications are generally viewed as more appropriate when considered from a partner''s perspective, especially for changeable attributes. However, these modifications are perceived as less acceptable in professional settings such as workplaces. Additionally, individuals with high self-monitoring tendencies tend to be more resistant to changes, while those scoring higher on Machiavellianism are more accepting of changes, particularly regarding unchangeable attributes and emotional expressions. These findings provide valuable insights for platform developers and designers, highlighting the importance of implementing context-aware customization options that balance core identity elements with personality-driven preferences, thereby enhancing user experiences while respecting social norms.' WHERE id = 43687;

-- id=43690 source=openalex_title | Gender Differences and Similarities in Entrepreneurship in European Countries: Latest Data
UPDATE papers SET authors = 'Vasiliki Zarogianni, Stavroula Laspita, Katerina Sarri', snippet = 'Abstract This paper explores gender differences and similarities related to entrepreneurship within European countries, using the latest data from the Global University Entrepreneurial Spirit Students Survey (GUESSS). We examine factors including entrepreneurial self-efficacy, resilience, life satisfaction, machiavellianism, narcissism, performance outcomes, and lean startup practices. Key findings reveal (among others) significant differences in economic and social performance between genders, with males typically reporting better economic performance and females exhibiting stronger social performance. The implications of these results are critical, suggesting the need for tailored support mechanisms to enhance female entrepreneurs’ performance and reduce gender differences in entrepreneurship.' WHERE id = 43690;

-- id=43692 source=page_meta | Revisiting Political Skill: When and How it Matters for Employee Performance Across Differ
UPDATE papers SET authors = 'Enny Marlinah Manggor, Ida Rosnita Ismail, Azizan Morshidi, Meliza Zafrizal, Muhammad Shofiyuddin', snippet = 'HRMARS - Political skill has been increasingly recognized as a pivotal determinant of workplace effectiveness, yet its influence on job performance remains conceptually and empirically fragmented. While numerous empirical studies have examined the relationship between political skill and employee performance, there remains a lack of cumulative knowledge on when political skill is most beneficial and how it enhances various dimensions of job performance. To address this gap, this paper conducts a systematic narrative review to synthesize theoretical and empirical insights, offering a more holistic perspective on the role of political skill in workplace settings. Specifically, this study explores (1) the unidimensional direct influences of political skill on different aspects of employee performance, (2) its relevance across diverse occupational and organizational contexts, and (3) the distinct contributions of its sub-dimensions in shaping employee effectiveness. By identifying critical theoretical gaps and empirical inconsistencies, this paper outlines a forward-looking research agenda to refine the conceptualization of political skill and its practical significance in contemporary work environments.' WHERE id = 43692;

-- id=43694 source=openalex_title | Unveiling the hidden dynamics: A configurational analysis of personality traits, demograph
UPDATE papers SET authors = 'Andreas Kallmuenzer, Rashid Khurshid, Hafiz Muhammad Usman Khizar, Jingbo Yuan', snippet = 'Knowledge Hiding is a pervasive problem in the workplace, which can have various negative consequences for individuals and organizations. Drawing from the underpinning of complexity theory, this study investigates the complex causal interrelationships associated with knowledge hiding in the workplace. That is, we explore the interrelationships of individual-level factors: i) demographic characteristics (age, gender, education and experience), and ii) personality traits (i.e., Big-5 and the Dark Triad), and knowledge hiding behaviours. We collected data from 157 employees in the hospitality sector and analyzed by using fuzzy-set qualitative comparative analysis (fsQCA). Our results highlighted multiple configurations of the demographic characteristics and personality traits (i.e., causal conditions) leading to knowledge hiding behaviours (i.e., outcome). Our findings revealed a total of 25 unique profiles combining personality traits and demographics factors–14 associated with the presence of knowledge hiding, and 11 linked to its absence. In particular, Machiavellianism emerged as a core condition driving the presence of knowledge hiding, while extraversion was identified as a core condition associated with its absence. This is the first-ever study comprehensively investigating distinct profiles resulting from the interplay between employees'' personality traits and demographic factors associated with their knowledge hiding behaviour.' WHERE id = 43694;

-- id=43695 source=openalex_title | Comparative analysis of Dark Triad traits in relation to performance and self-reported emo
UPDATE papers SET authors = 'Louana Marie Denogent, Alberto Megías‐Robles, Pablo Fernández‐Berrocal, Raquel Gómez‐Leal', snippet = 'Interest in the Dark Triad (DT) traits - Machiavellianism, narcissism , and psychopathy - and their association with maladaptive behaviors has surged in recent years. Research has focused on identifying protective factors such as Emotional Intelligence (EI), but the literature has yielded mixed results regarding this relationship. Our study seeks to explore this relationship from two distinct perspectives of EI: self-report and performance-based measures. To achieve this aim, 222 participants (M age = 22.01, SD = 4.54, ages 19–60) completed the Trait Meta Mood Scale (TMMS), a self-report measure, and the Mayer Salovey Caruso Emotional Intelligence Test (MSCEIT), a performance-based assessment, to evaluate EI, and the Short Dark Triad (SD-3) was used to evaluate DT traits. Our findings revealed a significant negative correlation between the traits of psychopathy and narcissism and EI scores when using the MSCEIT. However, when utilizing the TMMS, we only identified a positive and significant association between narcissism and EI. These findings underscore the importance of considering the type of EI measurement when examining this relationship. Moreover, we identified sex differences in the study variables and found that sex plays a moderating role in the studied relationship. We discuss the limitations and clinical implications of these findings.' WHERE id = 43695;

-- id=43697 source=openalex_title | Analysis of The Influence of Professionalism Attitude And Organizational Culture in Ethica
UPDATE papers SET authors = 'Ana Dwi Rahmawati, Yunus Handoko, Ike Kusdyah Rachmawati', snippet = 'Research Aims: Tax consultants have an important role in increasing the amount of state tax revenue, this study aims to explore the important role of tax consultants in ethical decision making based on professional attitudes, organizational culture and Machiavellianism. Design/methodology/approach: Used a quantitative approach through statistical analysis of data sources originating from tax consultants who are members of the Malang Branch of IKPI, data analysis was carried out by solving Structural Equation Modelling. Research Findings: The study indicate that organizational culture and Machiavellianism have an effect on encouraging ethical decision making by tax consultants, but not for professionalism. Machiavellianism is not able to be a mediating variable in this relationship. Theoretical Contribution/Originality: This research can directly and indirectly contribute academically and practically; academically, this research serves as a foundation for further research in research on organizational behaviors such as ethical decision making of tax consultants, with the inclusion of several additional variables, such as Machiavellianism, professional attitude and organizational culture.' WHERE id = 43697;

-- id=43700 source=openalex_doi | A bibliometric review of the consequences of narcissism among the top management team (TMT
UPDATE papers SET authors = 'Nana Adwoa Anokye Effah, Qinggang Wang, Gabriel Kyeremeh, Octavia Ama Serwaa Otchere', snippet = 'This paper adopts a bibliometric approach to review previous literature on how narcissism among TMTs impacts firm outcomes. By extracting data from the Web of Science core database from 2005-2022, the intellectual, social, and conceptual structure of articles in the business and management research domain is examined to ascertain the research activity on narcissism. Results show that the field is gradually advancing with more author and regional contributions. Nonetheless, author collaborations are few, and regional collaborations appear to be more concentrated in some specific regions. Thematic analyses revealed declining and relevant themes requiring further development, while emerging themes were assessed, highlighting avenues for future research. As themes such as auditor narcissism, luxury consumption, and audit quality emerge as niche themes, they highlight advancements in the scope of research within the business domain.' WHERE id = 43700;

-- id=43702 source=openalex_doi | Dark Triad Traits and Cyberbullying Perpetration: Addressing Current Limitations in Dark T
UPDATE papers SET authors = 'Karen T. Y. Tang, Luke R. Mungall, Julie Blais, Scott Pruysers', snippet = 'Cyberbullying remains a recurring problem in the digital age. Individual differences in Dark Triad personality traits (i.e., psychopathy, narcissism, Machiavellianism) have emerged as consistent predictors of cyberbullying. However, these findings may be affected by methodological limitations, including statistical partialing and the use of short, unidimensional, scales that conflate psychopathy and Machiavellianism. This study examined associations between cyberbullying perpetration and facets of psychopathy, Machiavellianism, and narcissism, while addressing the methodological shortcomings of previous studies. Canadian adults (N = 1,725) completed items pertaining to cyberbullying perpetration, along with the Self-Report Psychopathy Scale short form (SRP-4-SF), the Five Factor Machiavellianism Inventory (FFMI), the Narcissistic Grandiosity Scale (NGS), and the Narcissistic Vulnerability Scale (NVS). Confirmatory factor analysis supported the proposed structure of the SRP-4-SF, NGS, and NVS, but not the FFMI. Separate structural equation models were computed to estimate the association between each antagonistic trait and cyberbullying perpetration, controlling for age and sex. The antisocial facet of psychopathy and grandiose and vulnerable narcissism were significant positive predictors of cyberbullying perpetration. Cyberbullying prevention may be improved by designing interventions that account for the antisocial and narcissistic tendencies of cyberbullies. Focusing future research on narcissism and psychopathy would allow for greater scientific consilience within personality psychology.' WHERE id = 43702;

-- id=42818 source=openalex_doi | Exploring the mediating role of risk aversion in the relationship between personality trai
UPDATE papers SET authors = 'Jeevitha Elangovan, Michael David Premkumar, G. Yoganandan', snippet = 'Life insurance is a financial risk management tool for individuals. The intention to purchase a life insurance product was influenced by various demographic and psychological factors. The present study investigated the relationship between big five personality traits and life insurance purchase intention, with risk aversion as a mediator. The data was collected among 580 respondents and analysed using PLS-SEM. The results show that risk aversion has a positive significant effect on life insurance purchase intention and mediates the relationship of personality traits - conscientiousness, neuroticism, and openness to experience with life insurance purchase intention. The paper suggests that risk aversion and personality diagnostic tests can be conducted for the potential customers and the best possible life insurance products can be offered to them. This will aid the life insurance providers to have a long lasting relationship with the customers.' WHERE id = 42818;

-- id=42844 source=page_meta | The Relationship between Personality and Creativity in College Students: Mediating Role of
UPDATE papers SET authors = '彭依婷¹, 张英培¹, 王挺¹, 肖三蓉²', snippet = '目的：研究基于创造力发展的生态系统模型，以积极心理学视角，考察人格与创造力的关系，并检验心理韧性的中介及父母教养方式的调节作用。方法：采用心理韧性量表、中国大五人格问卷、父母教养方式问卷及威廉斯创造力倾向测量表对510名大学生进行问卷调查。结果：（1）人格特质能显著预测创造力，其中神经质显著负向预测创造力，其余四个维度均显著正向预测创造力；（2）心理韧性在人格特质与创造力的关系中起中介作用；（3）情感温暖调节了心理韧性和创造力之间的关系。高情感温暖时，心理韧性对创造力的影响更强。结论：培养积极稳定的人格特质、提高心理韧性和营造支持性的家庭环境，可以有效提升大学生的创造力。' WHERE id = 42844;

-- id=42848 source=page_meta | Trust Me, I'm Agreeable: The Role of Perceived Host Personality Traits in Airbnb Booking I
UPDATE papers SET authors = 'Fudurić, Morana, Puljić, Elena, Horvat, Sandra', snippet = 'Purpose – This study examines the role of host personality traits in perceived host reputation, trustworthiness, and booking intention on Airbnb. Specifically, it explores the role of verbal (host description and personality) and visual cues (host ph...' WHERE id = 42848;

-- id=42858 source=page_meta | The Influence of Linguistic Instructions on Personality Trait Manifestations in Large Lang
UPDATE papers SET authors = 'Xichen Fang', snippet = 'The rapid deployment of multilingual Artificial Intelligence (AI) systems necessitates rigorous assessment of linguistic factors in machine behavior patterns. Existing studies have primarily focused on monolingual personality expression in large language models (LLMs), leaving critical gaps in understanding how bilingual instruction sets modulate cognitive...' WHERE id = 42858;

-- id=42874 source=page_meta | The Influence of Employee Engagement and Big Five Personality on Employee Performance
UPDATE papers SET authors = 'Shofa Azzahra Aprilia', snippet = 'This study aims to analyze the influence of Employee Engagement and Big Five Personality on Employee Performance at PT. Geo Dipa Energi (Persero) Soreang. The research employs descriptive and verification methods, involving 80 employees as respondents. Pearson product-moment correlation and multiple linear regression analysis were used to test the hypotheses,...' WHERE id = 42874;

