-- export (6) v2 chunk 002 — 14 updates

-- id=45321 source=page_meta | Big Five Personality On Investment Decision: A Study On Peer-to-Peer Lending Companies In 
UPDATE papers SET authors = 'Indra Widjaja, Helena', snippet = 'Big Five Personality On Investment Decision: A Study On Peer-to-Peer Lending Companies In Indonesia' WHERE id = 45321;

-- id=45339 source=semantic_scholar_title | The relationships of personality traits on perceptions and attitudes of dentistry students
UPDATE papers SET authors = 'Furkan Ozbey, Yasin Yaşa', snippet = 'Artificial intelligence (AI) has gained significant attention in dentistry due to its potential to revolutionize practice and improve patient outcomes. However, dentists’ views and attitudes toward technology can affect the application of AI. This perception and attitude can be affected by the personality traits of individuals. This study aims to evaluate the perceptions and attitudes of dentistry students toward AI. This cross-sectional study was conducted on dental students at Ordu University Faculty of Dentistry, involving a sample of 83 students. The study utilized the Big Five 50 Test to evaluate personality traits and a 5-point Likert scale to gather data on 20 statements regarding AI in dentistry. Data were analyzed using IBM SPSS Statistics software, and a chi-square test was employed to assess the relationship between the personality traits of dental students and their attitudes towards artificial intelligence, as well as the relationship between the gender of dental students and their attitudes towards artificial intelligence. Statistical significance was set at P < 0.05. The study involved 83 participants, with 29 male and 54 female participants. The most common personality traits were Openness and Agreeableness, whereas the least common was Extraversion. Participants found AI useful and believed it could help dentists evaluate radiographs. However, the least agreed statement was that they would trust AI more than a dentist in evaluating radiograph results. A statistically significant difference was found between personal traits of dental students and in expressions comparing dentists and AI. Males were more familiar with AI than females. This study found that attitudes towards AI in dentistry vary based on personality traits. Developing educational strategies tailored to these traits can help foster more positive attitudes and improve AI integration into dental practice.' WHERE id = 45339;

-- id=45359 source=page_meta | Measurement of Destination Personality: An Updated Literature Review
UPDATE papers SET authors = 'Urooj  Zulfiqar, Harcharanjit  Singh, Asfandyar  Khan, Ikram- Ullah, Aliya  Yesmin, Zainab Mohammed  Alwan Al-Juboori', snippet = 'HRMARS - Destination branding has been an extensively investigated idea as governments and corporations seek to reposition their respective destinations&#039; images in the mainstream sphere. Many areas of destination branding are researched; not only for the purpose of branding or rebranding locations, but also to stimulate local economies. The purpose of this study is to obtain information about destination personality from the literature accessible in research sources. Based on the citation indices and downloads from digital sites and libraries, this research picked 28 noteworthy papers on the issue that were published in the recent 12 years, and then conducted the analysis on them. This review paper presents the findings of previous researches and the approaches used therein. The findings reveals that 42-item BPS of (Aaker, 1997) were used to measure destination personality. However, the most noticeable dimensions of destination personality based on which human characteristics are attributed to the destination are sincerity, excitement and conviviality and researchers used these dimensions are most commonly to measure destination personality. These noticeable dimensions of destination personality sincerity and excitement were found to be two main dimensions and conviviality is newly specific to destination. Researchers, marketers, and government officials might benefit from an increased understanding of notions of destination personality and its implications in tourism, which could lead to adjustments and improvements in the branding of tourist, business, and other kinds of destinations. Hence, it is essential to emphasise that this paper is only a qualitative evaluation of the literature and therefore confined to the results of prior research in this area.' WHERE id = 45359;

-- id=45365 source=page_meta | Exploring the Relationship Between Realistic Optimism and Big Five Personality Traits Amon
UPDATE papers SET authors = 'Nishaat, Aneesah', snippet = 'This study explores the relationship between realistic optimism and the Big Five personality traits among Indian university students, offering insights into these constructs in a non-Western context. Realistic optimism, emphasizing a hopeful yet grounded perspective toward the future, was measured using Nishaat&#039;s (2018) Realistic Optimism Scale, while personality traits were assessed using the Ten-Item Personality' WHERE id = 45365;

-- id=45368 source=page_meta | Effect of the Big Five Personality on the Intention to Use mHealth Applications among the 
UPDATE papers SET authors = 'Chang, Jinghui, Li, Anqi, Yang, Xixi, Li, Chunnan, Mai, Yanshan, Zhang, Dayi, Yan, Wende, Wu, Yibo, Chen, Jiangyun', snippet = 'BackgroundMobile health applications may provide potential tools to support healthy aging. Promoting mHealth use by the elderly remains an imperative to realize health improvement.ObjectiveThe research aimed to identify the relationship between personality traits and the intention to use mHealth applications among the elderly in mainland China.MethodsUsing a multi-stage sampling method, a cross-sectional survey of 3,712 older adults across China was obtained out of 3,721 (validity rate was 99.76%) in 2022. The effect of personality on the intention to use mHealth applications among older adults was analyzed by multiple linear regression. The independent variable was the personality, using the short version of the Big Five Personality Inventory (BFI-10). The dependent variable was the intention to use the mHealth applications, measured using a sliding scale. Moderators included demographic characteristics and psycho-social variables measured by the Perceived Social Support Scale, the Family Health Scale, and the Health Literacy Scale.ResultsThe Chinese older adults’ intention to use mHealth applications scored (63.31 ± 25.09). Out of the five traits, extraversion, agreeableness, and openness exerted significant effects. Higher scores of extraversion (β=0.59, t = 1.99, p<0.05) and openness (β=1.87, t = 6.07, p<0.01) contributed to the intention to use mHealth applications. Conversely, higher agreeableness scores (β= − 1.05, t = −3.12, p<0.01) related to lower intention.ConclusionThe elderly with high extraversion, openness, and low agreeableness are more willing to adopt mHealth applications in China. Healthcare professionals and mHealth device developers can make personalized and accurate interventions for the elderly with different personalities.' WHERE id = 45368;

-- id=45385 source=page_meta | Spouses' Personalities and Marital Satisfaction in Chinese Families
UPDATE papers SET authors = 'Jia, Li, Antonides, Gerrit, Liu, Zhuomin', snippet = 'IntroductionConsidering the traditional Confucian values prevalent in Chinese society, we study the effects of the spouses’ personalities and household sociodemographic circumstances on the marital satisfaction of marriage partners.MethodsWe evaluate the factors that contribute to marital satisfaction, using the 2018 wave of the Chinese Family Panel Survey, including 6,603 households. We use information on both spouses’ Big-Five personality traits, and marital satisfaction. In addition, the effects of the household’s sociodemographic factors on the spouses’ marital satisfaction are estimated. We employ the Actor–Partner Interdependence Model to estimate the effects, using simultaneous equation modeling.ResultsWe find significant actor effects of personality, i.e., agreeableness, openness, conscientiousness, and extroversion, but few partner effects on marital satisfaction. In addition to other socioeconomic effects, we find strong actor effects of subjective social status on marital satisfaction for both spouses. The wife’s level of education had a negative effect on her marital satisfaction.DiscussionThe effects of the spouses’ personalities and sociodemographic circumstances on their marital satisfaction fit the Confucian values fostered in China. The wife’s double burden of having a job and taking care of household duties, negatively affecting her marital satisfaction, may be alleviated by proper government policies.' WHERE id = 45385;

-- id=45386 source=semantic_scholar_title | The technology acceptance
UPDATE papers SET authors = 'Ronny Scherer, Fazilat Siddiq, J. Tondeur', snippet = 'Abstract The extent to which teachers adopt technology in their teaching practice has long been in the focus of research. Indeed, a plethora of models exist explaining influential factors and mechanisms of technology use in classrooms, one of which—the Technology Acceptance Model (TAM) and versions thereof—has dominated the field. Although consensus exists about which factors in the TAM might predict teachers’ technology adoption, the current field abounds in some controversies and inconsistent findings. This meta-analysis seeks to clarify some of these issues by combining meta-analysis with structural equation modeling approaches. Specifically, we synthesized 124 correlation matrices from 114 empirical TAM studies (N = 34,357 teachers) and tested the fit of the TAM and its versions. Overall, the TAM explains technology acceptance well; yet, the role of certain key constructs and the importance of external variables contrast some existing beliefs about the TAM. Implications for research and practice are discussed.' WHERE id = 45386;

-- id=45390 source=page_meta | Disengaged on Day 0: How Antecedent Disengagement May Be a Key Factor in Attrition in the 
UPDATE papers SET authors = 'David Troy', snippet = 'In recent decades, a large amount of research has emerged in organizational psychology regarding immutable personality traits and the intersection with organizational commitment and work engagement. T...' WHERE id = 45390;

-- id=45403 source=page_meta | On the Emergent Capabilities of ChatGPT 4 to Estimate Personality Traits
UPDATE papers SET authors = 'Piastra, Marco, Catellani, Patrizia', snippet = 'This study investigates the potential of ChatGPT 4 in the assessment of personality traits based on written texts. Using two publicly available datasets containing both written texts and self-assessments of the authors’ psychological traits based on the Big Five model, we aimed to evaluate the predictive performance of ChatGPT 4. For each sample text, we asked for numerical predictions on an eleven-point scale and compared them with the self-assessments. We also asked for ChatGPT 4 confidence scores on an eleven-point scale for each prediction. To keep the study within a manageable scope, a zero-prompt modality was chosen, although more sophisticated prompting strategies could potentially improve performance. The results show that ChatGPT 4 has moderate but significant abilities to automatically infer personality traits from written text. However, it also shows limitations in recognizing whether the input text is appropriate or representative enough to make accurate inferences, which could hinder practical applications. Furthermore, the results suggest that improved benchmarking methods could increase the efficiency and reliability of the evaluation process. These results pave the way for a more comprehensive evaluation of the capabilities of Large Language Models in assessing personality traits from written texts.' WHERE id = 45403;

-- id=45405 source=semantic_scholar_title | Personality trait and employee performance in digital transformation: the mediating effect
UPDATE papers SET authors = 'S. Subramaniam, Magiswary Dorasamy, C. Malarvizhi', snippet = 'Abstract The nature of the digital age requires organisations to change their model and adapt to the demands to successfully maintain organisational legitimacy. The pressure on public sector organisations to transform at a higher-than-normal rate cannot be overemphasised; therefore, understanding employees’ capabilities is imperative for starting a systemic change. Personality traits are considered to be important determinants for improving individual performance. Employees’ personality traits in handling the digital environment determine the extent of digital transformation implementation in the public sector. Thus, the purpose of this research is to conceptualize approaches towards measuring the performance of public sector employees in Malaysia with particular attention to the Employee Dynamic Capability Model. The research method applied in this study was quantitative, and data were collected using an online questionnaire. SmartPLS software was used for the data analysis. The Big Five personality traits (agreeableness, conscientiousness, openness and neuroticism) were found to have a significant relationship, while extraversion was not. This study further extends the current body of knowledge by examining the dynamic capability of the employee as a mediator in the current research and provides directions for subsequent researchers focusing on employee performance in the context of the digital environment.' WHERE id = 45405;

-- id=45413 source=page_meta | Enhancing Work Engagement through Personal Growth: Unmasking Neuroticism's Influence
UPDATE papers SET authors = 'Ruchi Sao, Shravan Chandak, Simran Manthapurwar, Gouri Teje', snippet = 'Welcome to the home page of the Journal of Informatics Education and Research for Finance, Mortgages and Insurance. We are a premiere organization dedicated to the study and promotion of knowledge on mortgages and various types insurance. The plan for the Journal of Informatics Education and Research for Finance and Insurance was hatched in a meeting in 1993 between members of the different brokerage companies throughout the United States. The first issue came out in January 1994. From twenty subscribers in its first year, the number of the Journal has climbed steadily. It now currently has 8,000 subscribers. The first issue was sent to subscribers in June and the second issue was sent out in December of each calendar year. Editors of the Journal of Informatics Education and Research for Finance and Insurance organize a yearly forum discussing the whole gamut of mortgages and insurance products as well as the latest developments in the industry. Freelance agents stand to gain the most benefit from what the Journal has to offer. For example a recent issue we ran delved into the statistics of senior citizens and their interaction with a reverse mortgage calculator. You can subscribe to the the Journal of Informatics Education and Research for Finance and Insurance at any time of the year. You can register and subscribe and still get in upcoming issue. Subscribe now to the Journal and be enlightened.' WHERE id = 45413;

-- id=45425 source=semantic_scholar_title | The Role of the Big Five Personality Test to Understand Yourself in the Modern and Multicu
UPDATE papers SET authors = 'Z. Zubaidah, Dania Riski Rahayu, Syifa Azzahra Silvir, M. H. Silvir', snippet = 'In the midst of the ongoing development of globalization, the importance of understanding individual personality is increasingly significant. This article explores innovations in the BIG FIVE Test, which is a tool that has proven effective in evaluating personality dimensions such as openness, conscientiousness, extraversion (sociability), agreeableness, and tendency toward anxiety. With a more modern and relevant approach, this test not only helps individuals recognize themselves but also provides insights into interactions within a multicultural context. This article highlights how global factors, such as technological advancements, intercultural communication, and social changes, influence personality. The aim of this research is to emphasize the importance of adapting personality measurement tools to understand the complexities of individual identity in an increasingly interconnected world. It is hoped that the findings from this study can serve as a reference for professionals in psychology, education, and human resource development in creating more effective and inclusive programs.' WHERE id = 45425;

-- id=45432 source=page_meta | A Network Analysis Study on the Relationship between Generalized Anxiety Symptoms, Big Fiv
UPDATE papers SET authors = 'Yang, Jiaqin, Man, Xiaotong, Liu, Chunlei', snippet = 'IntroductionUnder the background of COVID-19, people’s mental health problems are concerned by researchers. Network analysis is a new method of exploring the interactions between mental health issues at the symptom level. This study investigates the network structure of generalized anxiety symptoms among Chinese residents during the COVID-19 pandemic from the perspective of “society-family-personality,” and explores its relationship with the Big Five personality traits and perceived social support.MethodsA multi-stage random sampling cross-sectional survey was conducted in 120 cities across China Mainland from July 10, 2021 to September 15, 2021, based on the PBICR database. The Big Five Scale (BFI-10), Perceived Social Support Scale (PSSS), and Generalized Anxiety Scale (GAD-7) were used for measurement. Pearson correlation analysis was used to examine the variables mentioned in this research, and network analysis was used to estimate the psychopathological network of the three variables.ResultsA total of 11,031 subjects were included in the study, with 17% of individuals suffering from severe generalized anxiety symptoms. The results showed a correlation between the three research variables, and it was found that perceived social support in both dimensions and agreeableness of the Big Five personality traits were at the center of the network, with a significant impact on the overall network. There is a positive correlation between agreeableness and family support, but a negative correlation with generalized anxiety symptoms. Agreeableness serves as an indicator linking the other two variables; No significant gender differences were found through gender network testing.ConclusionAccording to this study, we believe that interventions in family atmosphere and social interaction can be used to prevent symptoms of generalized anxiety disorder. The limitation of this study is that it cannot determine the causal relationship between variables and its generalizability…' WHERE id = 45432;

-- id=45447 source=semantic_scholar_title | Assessing the Impact of Big Five Personality Traits on Job Performance: A Study in Associa
UPDATE papers SET authors = 'S. Harikaran, D. M. C. Dassanayake', snippet = 'The flourishing life insurance industry in Sri Lanka underscores the pivotal role of insurance agents in advancing revenue streams and overall success. This study examines the nexus between the Big Five personality traits and the Job performance of insurance agents in the life insurance companies in the Northern Province of Sri Lanka. The independent variables encompass the dimensions of openness to experience, conscientiousness, extraversion, agreeableness, and emotional stability, while the dependent variable comprises job performance. A stratified random sampling approach was employed to distribute 300 structured questionnaires among insurance agents in life insurance companies. The collected data were analyzed by using different statistical techniques. The outcomes of the multiple regression analysis underscore a substantial impact of all Big Five personality dimensions excluding agreeableness on job performance. These findings offer valuable insights for insurance agents, aiding them in making informed career choices. Simultaneously, life insurance company managers can leverage this research to refine their selection criteria, ensuring the recruitment of individuals whose personalities align with the dimensions that significantly impact job performance in the industry and identify the training needs for the personality development of the insurance agent in the life insurance companies in Sri Lanka.' WHERE id = 45447;

