-- export (6) v2 chunk 006 — 57 updates

-- id=43714 source=openalex_title | Research on Similarity of Fictional Characters Based on Enhanced Convolutional Neural Netw
UPDATE papers SET authors = 'Bao Xinli', snippet = 'The increase in utilization of social media as a platform for self-understanding and self-expression which lead to increased use of Myers–Briggs Type Indicator (MBTI) to discover personality similarities of fictional characters. However, similarity analysis of fictional character personality has limitations due to irrelevant features, and long length sentences. To overcome these limitations, an Enhanced Convolutional Neural Network (ECNN) model is proposed to predict and analyze similarity of fictional characters'' personality traits in text-based data. The ECNN model utilize a global average election pooling activation layer and modification in convolutional layer enhance prediction and analysis of personality traits accurately. The data is preprocessed using tokenization, stemming and stop words removal to enhance performance by removing unwanted texts and split long sentence into small parts. These texts are converted into vectors by CountVectorizer technique which helps to analyze similarity of characters easily. Experimental results show that proposed prediction model achieve accuracy of 94.88% which is higher than existing model like Naïve Bayes, Long Short-Term Memory and Logistic regression.' WHERE id = 43714;

-- id=43717 source=openalex_title | Identifying Personality Types of Mayors in Local Government in Bulgaria According to the M
UPDATE papers SET authors = 'Loreta Traykova', snippet = 'In this article, we make an attempt to explore and identify the personality types of mayors in Bulgarian local government by applying the Myers-Briggs typology indicator. This article presents part of the results of a more extensive authorâ€™s survey of mayors in municipalities and districts across the country. The fieldwork was carried out in the period between June 2022 and September 2023, with responses received from 57 of the mayors. The attention will be directed towards one of the questionnaires applied in this authorâ€™s study, which included questions regarding leadership models in Bulgarian municipalities. The methods used to analyze the collected data are descriptive statistics and calculation of an arithmetic mean value. The analysis identifies personality types of Bulgarian mayors and the strengths and weaknesses for each type. The results show that the personality type â€˜Executiveâ€™ is the most common one among mayors in Bulgarian municipalities. The results provide an opportunity to expand the research and include qualitative methods such as in-depth interviews, focus groups and others, with the aim of examining the specifics of the individual case and linking it to the context of the environment. In addition, in the future, the relationship between personality type, charisma, emotional intelligence and the managerial style of the mayors will be investigated, as a result of which a profile can be built, through which candidates for public positions can be selected. Further research will also look at the relationship between the personality type of the mayor, the financial and economic condition of the municipality and the attracted investments during their mandate term.' WHERE id = 43717;

-- id=43718 source=openalex_doi | Research on audience psychological communication in the era of new media--taking the MBTI 
UPDATE papers SET authors = 'Xiaofei Fan', snippet = '\nThis article adopts a literature analysis method, taking the popular phenomenon of MBTI（Myers Briggs Type Indicator） in the current era of new media as the background, aiming to study the emergence and development process of MBTI from the perspective of audience psychology. The author conducts analytical research on communication psychology-related theories such as usage and satisfaction, selective contact hypothesis, and interest groups, deeply explores the application of MBTI in audience psychology research, analyzes its value in understanding audience behavior and psychological characteristics, and explores its challenges and prospects in practical applications. While MBTI has become popular, it has also brought some negative orientations due to its labeling, such as stereotypes and group anxiety. The fanaticism and initiative exhibited by individuals in the congenial group trigger group effects through communication. In the era of new media, with the rapid development of various media matrices, how to rationally view the emotional interactions of individuals and even groups constructed by MBTI, how to use the power of new media to correctly meet audience needs, and how to make the emergence and dissemination of MBTI conform to the benign trend of social development are all issues worthy of in-depth research.\n' WHERE id = 43718;

-- id=43719 source=openalex_doi | Exploring connections between prayer preferences and psychological type or temperament: In
UPDATE papers SET authors = 'Leslie J. Francis, Christopher C. H. Cook, Ursula McKenna', snippet = 'Building on earlier research concerned with connections between prayer preferences and psychological type or temperament, the present study focused specifically on prayer preferences associated with the orientations (extraversion and introversion) and the attitudes (judging and perceiving). Drawing on data provided by 207 Anglican and Methodist ministry training candidates this study proposed and tested the Durham Indices of Prayer Preferences (DIPPs), comprising four eight-item scales of extraversion prayer preference, introversion prayer preference, judging prayer preference, and perceiving prayer preference. Each scale demonstrated good properties of internal consistency reliability and construct validity tested against the psychological type preferences of the participants as assessed by the Myers-Briggs Type Indicator.' WHERE id = 43719;

-- id=43720 source=openalex_title | Fluid Modernity and Virtual Communities: An Analysis of the Popularity of MBTI on Social M
UPDATE papers SET authors = 'M J Wang', snippet = 'This paper, rooted in Zygmunt Bauman’s theory of modernity, examines the formation of virtual communities and the characteristics of liquid modernity as manifested in the widespread phenomenon of Myers-Briggs Type Indicator (MBTI) on social media. As a psychological assessment tool, MBTI has pervaded social media platforms, engendering virtual communities characterized by high fluidity and consumerist tendencies. Through participatory observation and online ethnography, this study delves into the MBTI virtual communities on the "Xiaohongshu" platform, exploring their consumerism-driven formation mechanisms and cultural attributes. In modern society, virtual communities exhibit dynamic stability and structural elasticity, with identity constantly being reshaped and redefined within these virtual spaces. The popularity of MBTI underscores the anxieties surrounding identity in contemporary society and reflects the liquid nature of modern identity formation. Under the influence of technology and consumerism, virtual communities have emerged as a significant social form in modern society.' WHERE id = 43720;

-- id=43721 source=openalex_title | The Relationship between the Myers-Briggs Type Indicator (MBTI) Types and Psychological We
UPDATE papers SET authors = 'Wang Liying, Shahnaz Sheibani', snippet = 'Aim: This study explores the relationship between Myers-Briggs Type Indicator (MBTI) personality types and psychological well-being among Chinese college students, examining how cultural factors influence this relationship and identifying key factors impacting students'' mental health. Methodology: A systematic literature review was conducted, focusing on peer-reviewed articles from the past decade. Databases such as PubMed, PsycINFO, and Google Scholar were searched using keywords like "MBTI," "psychological well-being," "college students," and "China." Inclusion criteria included studies on MBTI and psychological well-being among Chinese college students. Results: The review found that 64% of extraverted students reported high life satisfaction, compared to 42% of introverted students. Sensing students showed 58% academic satisfaction, while only 45% of intuitive students reported similar satisfaction levels. Thinkers (60%) and feelers (55%) displayed high psychological well-being linked to their respective environments. Judging types reported 70% life satisfaction, whereas only 45% of perceiving types expressed similar satisfaction. These findings underscore the significant impact of MBTI personality types on the psychological well-being of Chinese college students. Conclusion: MBTI types significantly influence psychological well-being among Chinese college students, moderated by cultural, social, and educational factors. Tailored mental health interventions and supportive environments are essential to address the diverse needs of students. Recommendations: Colleges should integrate MBTI-based counseling services, provide flexible learning options, and promote social support networks. These measures will accommodate varying personality types and improve overall student well-being. Implications: Understanding the interplay between MBTI types and psychological well-being within the Chinese cultural context offers valuable insights for educators and mental health…' WHERE id = 43721;

-- id=43722 source=openalex_title | The Relationships between the Myers-Briggs Type Indicator (MBTI), Job satisfaction and Wel
UPDATE papers SET authors = 'Wang Liying, Shahnaz Sheibani', snippet = 'The phenomenon of working college students is on the rise in China. Evidence elsewhere suggests that working while studying can be problematic for students'' well-being. This research sought to assess whether personality types and job satisfaction can be used to prevent the decline of well-being among working college students in the country. It specifically examined the effects of Myers-Briggs Type Indicator (MBTI) types on job satisfaction and well-being, relationship between job satisfaction and well-being wellbeing, and the moderating roles of field of study and emotional state in these relationships. Based on the findings, these objectives have been successfully met. The findings show that MBTI personality types significantly shape both job satisfaction and well-being. Scoring highly on Extraversion, Sensing, Thinking, and Judging predicts high job satisfaction and better well-being among the students. Job satisfaction was also found to positively impact well-being for working students. Additionally, the findings also show that the field of study and emotional state moderate the stated relationships. The findings of this study are sound as they generally align with what other researchers have established. The findings imply that Myers-Briggs Type Indicator (MBTI) types and job satisfaction can be applied and targeted to enhance the well-being of working college students in China as the phenomenon continues to grow.' WHERE id = 43722;

-- id=43723 source=openalex_doi | Unravelling the Relationship Between Personality Traits and Learning Styles: Implications 
UPDATE papers SET authors = 'Shahrul Mizan Ismail', snippet = 'This study investigates the correlation between personality traits and learning styles among university students, with the aim of identifying patterns that can enhance personalized educational strategies.Drawing on the Myers-Briggs Type Indicator (MBTI) framework and VARK (Visual, Auditory, Reading/Writing, Kinesthetic) learning styles, the study analyzes data from 77 students to understand how their personalities align with specific learning preferences.Findings reveal a predominance of visual learners and highlight recurring personality types such as INFJ (Advocate) and ENTJ (Commander).The analysis emphasizes the need for diversified teaching approaches to foster engagement and learning outcomes across different learner profiles.This research not only fills the existing gap in educational psychology but also offers actionable recommendations for educators, providing a foundation for future studies on personalized learning environments.' WHERE id = 43723;

-- id=43725 source=openalex_title | Synonym Replacement Augmentation for Handling Data Imbalance in Personality Classification
UPDATE papers SET authors = 'Rilo Chandra Pradana, Derwin Suhartono', snippet = 'The Myers-Briggs Type Indicator (MBTI) classification is a widely utilized instrument for personality assessment. However, it frequently encounters challenges due to imbalanced data distributions across personality dimensions. It is paramount to address this issue to enhance the accuracy and reliability of personality predictions. Most current research in this field is focused on data balancing techniques, such as oversampling and undersampling, which have been demonstrated to enhance model performance. Nevertheless, there is a dearth of research exploring text augmentation methods, particularly synonym replacement, for this purpose. This study examines the efficacy of synonym replacement as a data augmentation technique for MBTI classification. Experiments are conducted with varying levels of synonym replacement (10%, 30%, 50%, 70%, and 90%) to assess its impact on model accuracy and F1 scores across the four MBTI dimensions. Our findings indicate that low levels of synonym replacement, particularly at 10% to 50%, can enhance the performance of the model in predicting MBTI dimensions. On the other hand, a higher number of replaced words in the synonym replacement augmentation can harm the model''s performance. These observations suggest that synonym replacement can effectively address data imbalance in MBTI classification, although its application must be tailored to specific personality dimensions.' WHERE id = 43725;

-- id=43727 source=page_meta | How Good Is The Myers-Briggs Type Indicator For Predicting Leadership-Related Behaviors?
UPDATE papers SET authors = 'Zárate-Torres, Rodrigo, Correa, Juan C.', snippet = 'The Myers-Briggs Type Indicator (MBTI) is a popular tool used by psychologists working as managers'' coaches in organizational contexts. Despite its popularity, few studies provide empirical evidence on the role of the MBTI as a predictor of managers'' leadership-related behaviors. \textcolor{blue}{This article is written based on research that answers the question of how good the MBTI is to prove leadership behavior. It does so by comparing goodness-of-fit indexes of two confirmatory factor analysis models and two structural models on the personality-leadership relationship, following standards of reproducible research principles. We sampled 529 participants who were graduate andundergraduate students enrolled in business administration programs from Colombian universities}. Results show conclusive evidence of the psychometric measurement of both MBTI and leadership practices, even though the relationship between MBTI and the leadership practices inventory proved to be weak.' WHERE id = 43727;

-- id=43730 source=openalex_doi | Do you love traveling to the beach or mountain? Predicting personality traits and choice b
UPDATE papers SET authors = 'Sanjit Kumar Roy, Hsiu‐Yuan Tsao, Ching-Chang Lin, Gaganpreet Singh, Hui-Yi Lo', snippet = 'Several personality-predicting tools are being used by managers in their strategic decision-making process. The most common are the Big Five model and the Myers – Myers-Briggs Type Indicator model, respectively. This study deviates and tests a novel personality prediction model. Specifically, it utilizes the TF-IDF (Term Frequency-Inverse Document Frequency) algorithm as a feature extraction method to map personality traits based on consumers’ textual data from the Kaggle MBTI Personality Type dataset. This study uses realistic data gathered from traveller reviews and comments on hotel stays from TripAdvisor’s widely recognised platform to predict different personality traits and their travel destination preferences, i.e. beach or mountain. The contribution of this study lies in the identification of multiple dimensions of peoples’ personality traits and their relationship with their preferences for travel locations. This proposed trait classification mechanism can assist marketing managers in effectively carrying out customer segmentation, setting realistic goals, and optimizing marketing strategies.' WHERE id = 43730;

-- id=43734 source=openalex_doi | Personality Tag: Interactive Artwork with Style Transfer for Personal Expression
UPDATE papers SET authors = 'Yuxuan Bai, Yaqing Cai, Leyan Huang, Runze Tian, Pan Hui, Varvara Guljajeva', snippet = 'Personal traits are often concealed within the minutiae of one’s daily life. A deeper understanding of an individual requires sustained interaction with each other. However, in certain social settings, we must quickly reveal ourselves within a group and engage in conversation to "break the ice." This necessitates using symbolic "tags" to describe oneself, such as personality types identified by the Myers-Briggs Type Indicator (MBTI). With its popularity in recent years, showcasing individual traits in interactions. Building on this, we propose an innovative interactive artwork whose research question is how artwork can utilize visualization techniques to create images that embody personalities based on the MBTI classification. Utilizing the Design-Based Research (DBR) method, we combine MBTI with style transfer technology to visually express personal characteristics, aptly termed "personality tags." In a user test, we invited 12 users to experience our work. Eleven of them believed that the generated images partially reflected their personality. Based on this, we believe this artwork underscores the potential of style transfer to enhance graphical visualization and personal expression.' WHERE id = 43734;

-- id=43735 source=openalex_doi | Personality Typing, Anyone? The Myers-Briggs Personality Indicator
UPDATE papers SET authors = 'Matthew Alexander, Kelly Breen Boyce, Leslie L. Pitt, Kevin M. Krause', snippet = 'THE MYERS-BRIGGS TYPE INDICATOR (MBTI) HAS BEEN CALLED “THE world’s most widely used personality assessment tool,” 1 with estimates of as many as two million annual assessments. Based on the theories of Carl Jung and developed by Katharine Cook Briggs and her daughter Isabel Briggs Myers, the MBTI is routinely used in business, couple therapy, career counseling, leadership training, and education. The MBTI measures personality by typing psychological preferences along four scales: (1) Extrovert-Introvert, (2) Thinking-Feeling, (3) Sensing-Intuition, and (4) Judging-Perceiving. These four dichotomies make 16 possible combinations and these are called “types.” Four basic temperaments can be found among the 16 types. 2 Although variations have been observed, studies have shown strong support for construct validity, internal consistency and test-retest reliability of the MBTI. 3–5' WHERE id = 43735;

-- id=43739 source=semantic_scholar_title | How to avoid gifts from your patients after the Christmas holidays?
UPDATE papers SET authors = 'Q. Richier, Dorothée Fey, Mary Kate Kelly, Shakeel Sumodhee, Achille Raviez, B. Glémain', snippet = 'BACKGROUND Receiving gifts from patients could generate an ethical dilemma for physicians and refusing a present may be perceived as an offence. OBJECTIVE To differentiate the particular physician characteristics that are associated with receiving gifts from outpatients. To propose a strategy to avoid gifts and thus ethical dilemma. DESIGN A prospective and multicentric study in France during the month of January 2024. SETTING Public hospitals, private hospitals and family practices across 20 cities in France. PARTICIPANTS Physicians from 21 medical and surgical specialities. Setting Public hospitals, private hospitals and family practices across 20 cities in France. INTERVENTIONS Each physician completed a questionnaire that highlighted their habitual practices during consultations and recorded the gifts they received on a standardized gift calendar. MAIN OUTCOMES MEASURES Receiving at least one gift during January 2024. RESULTS In total, 655 physicians were contacted before December 31st, 2023, 109 (16.6%) positively responded, of them 76 (70%) declared receiving at least one gift from patients. An experience>10 years in the current job (P=0.04), being the "Explorer" Myers Briggs Type Indicator (MBTI) personality type (P=0.034), and a frequent delay of over 30minutes at the end of the day of consultations (P=0.048) were statistically associated with a higher likelihood of receiving at least one gift from patients in multivariate analysis. The physicians who received the most gifts per 100 consultations were those with over 10 years experience and those who fell under the MBTI personality role "Explorer": 2.72 (IQR [1.56-7.55], P=0.029) and 3.33 (IQR [2.16-6.43], P=0.028), respectively. CONCLUSION After analysing the factors that increase the risk of receiving a gift from a patient, we have surmised the following advice for physicians who do not wish to find themselves in the midst of an ethical dilemma. They should avoid staying in the same service for more than…' WHERE id = 43739;

-- id=43740 source=openalex_title | Clustering MBTI personalities with graph filters and self organizing maps over Pinecone
UPDATE papers SET authors = 'Γεώργιος Δρακόπουλος, Phivos Mylonas', snippet = 'Self organizing maps (SOMs) or cognitive maps are designed to preserve major topological attributes of manifolds in a higher dimensionality data space to corresponding projections thereof in a low dimensional coordinate space. This is performed by mapping neighborhoods and the distances contained therein from the data space to ones in the coordinate space. Thus, SOM functionality relies heavily on the geometrical properties of both spaces. Topologically flexible data space distance metrics are constructed by combining tensors with graph filters, the latter coming from graph signal processing. The power of these distance metrics comes from naturally expressing the higher order relationships between points of the data space. This paves the way for addressing engineering scenarios involving a large number of densely interrelated attributes. One such case is discerning personalities from textual information based on the Myers-Briggs taxonomy indicator (MBTI), a framework of archetypal personalities derived from Jungian psychodynamic theory. Various graph filters were tested on a benchmark Kaggle dataset with ground truth with comparisons assessed in terms of topological error, cluster purity, average inter-cluster distance, and cluster curvature variability. Data points were stored in Pinecone, a recent vector database, with Python integration.' WHERE id = 43740;

-- id=43743 source=openalex_doi | A Study on the Factors Affecting Mood Level and Variability-Focusing on Sasang Constitutio
UPDATE papers SET authors = 'Esther Jang, Soo-min Jo, Hyeo-woo Jeong, Kyeong-ok Kim', snippet = 'As a previous study to determine the factors influencing the level and variability of Chiljeong, the influence of Sasang Constitution and MBTI preferences on mood level and variability was examined. Among the 87 students of Korean Medicine attending D University who completed the Sasang Constitutional test and MBTI personality test, a Mood Survey was conducted and 83 of them were selected. Data were analyzed using the chi-squared test, ANOVA, independent sample t-test, and nonparametric test in IBM SPSS 22.0 for Windows. The mood level in Sasang Constitutions was highest in Soyang-in and Soeum-in, while Taeeum-in, Taeyang-in, and unclassified showed no differences. There was no difference in mood variability among Sasang Constitutions. The mood level was influenced by the direction of energy of MBTI preferences. There was no difference in mood variability between MBTI preferences. The mood level was influenced by Sasang Constitution and the direction of energy of MBTI preferences, but mood variability was not influenced by them.' WHERE id = 43743;

-- id=43745 source=openalex_title | Sistem Pakar Tes Kepribadian Myers Briggs Type Indicator Dengan Metode Forward Chaining
UPDATE papers SET authors = 'Hari Lugis Purwanto, Peri Adisa Putra', snippet = 'In personality tests, a psychologist not only focuses on the assessment process and data processing but also determines the test conclusions and determines the treatment for their clients. The assessment process is often handed over to assistants so that psychologists can focus more on doing more important things. To replace the role of psychologists in conducting assessments or the same and repetitive work, an expert system is needed. Psychologists will delegate their work to a computer system to support their work so that they will focus on more essential things, thereby helping to reduce the risk of error. One of the most popular methods for personality testing is the MBTI (Myers-Briggs Type Indicator) to find the potential and weaknesses of each client so that psychologists can focus on developing potential and improving client weaknesses. MBTI will be entered into the expert system as a knowledge base. In finding answers, the inference engine will track by matching knowledge-based rules with facts in the database using the forward chaining method. And as a result, the software that has been built can be used to analyze personality tests. The information generated helps psychologists to analyze human personality tests and be more efficient in dealing with client problems. Clients are also able to conduct independent tests to identify their own weaknesses and strengths, so that the development suggestions provided by the system can be used as a guide in suppressing their negative side and maximizing their positive side.' WHERE id = 43745;

-- id=43747 source=openalex_title | Introduction to the Theories and Modelling of Active Colloids
UPDATE papers SET authors = 'Panayiota Katsamba, Thomas D. Montenegro‐Johnson', snippet = 'This chapter will introduce the mathematics of modelling of active (autophoretic) colloids. It is intended to be something of a beginners’ guide, rather than an extensive literature review, and hopefully has useful information for theorist and experimentalist alike. The focus will be on modelling active colloids at the particle level, rather than at the suspension level via coarse-grained continuum methods. We first take a particle-centered view, whereby we consider the forces acting on a single sphere, to get Langevin dynamics – an ordinary differential equation (ODE) for the Janus particle’s motion. We discuss how the dynamics of a collection of such particles can be simulated by solving these ODEs together, and about how to add in physics – such as pair-wise fluid interactions between particles – to make the modelling more realistic. We then switch viewpoints to focus on what is going on outside the particle in the fluid, looking at the partial differential equations that govern the interactions of the solute fuel, particle, and the propulsive flows. We discuss some numerical techniques for studying autophoretic systems within this framework, with a focus on the Boundary Element Method. We present a method of simplifying this framework for slender autophoretic filaments and loops with arbitrary 3D shape and chemical patterning. In doing so, we see that the particle viewpoint and the fluid viewpoint “meet in the middle”, as we describe the interacting particles as a set of fundamental solutions with increasingly fast decay – point sources, dipoles, forces, torques, and stresses. We finish with a discussion of some potential future directions.' WHERE id = 43747;

-- id=43749 source=openalex_title | Mixture Kernel based Least Square Support Vector Machine for Personality Prediction on Soc
UPDATE papers SET authors = 'M. Jamuna Rani, Myasar Mundher Adnan, N. Naga Saranya, G. Karuna, G. Simi Margarat', snippet = 'The prediction of the human’s activities and the personality from the social media platforms attains significant growth between the researchers. The statistical data over the human activities represented through the social media platforms is important benefit for the analysis in the predictions of the personalities and other attitudes of the humans. However, the challenges in personality prediction are to introduce effective approach which determines an individual’s personality traits from various behavioural data. Hence, to tackle these issues, this research proposes the Mixture Kernel based Least Square Support Vector Machine (MK-LSSVM) approach for the personality prediction. The utilization of mixture kernels in SVM, enables for modelling the challenging relationships in the data, capturing various types of input features and enhancing the prediction accuracy. The standard datasets such as Essay and Myers-Briggs Type Indicator (MBTI) are utilized to implement the MK-LSSVM approach. The Term Frequency and Inverse Gravity Moment (TF-IGM) approach is utilized for the feature extraction, which determines the relationship between the feature sets and features from the datasets. The implemented results demonstrates that the MK-LSSVM approach reaches the superior average accuracy of 89.72% and average precision of 0.89 as compared to the CatBoost algorithm.' WHERE id = 43749;

-- id=43750 source=openalex_title | Personalisasi Gamifikasi Pembelajaran Transformasi Pendidikan Pemrograman Berbasis Mobile 
UPDATE papers SET authors = 'Tri Puspa Rinjeni, Virdha Rahma Aulia, Rafika Rahmawati, Tri Luhur Indayanti Sugata, Iqbal Ramadhani Mukhlis, Prasasti Karunia Farista Ananto', snippet = 'Penelitian ini mengeksplorasi potensi gamifikasi personalisasi dalam mengatasi tantangan keterlibatan dan motivasi dalam pendidikan pemrograman. Dengan memanfaatkan kerangka Myers-Briggs Type Indicator (MBTI), elemen gamifikasi seperti leaderboard, badges, dan progress bar disesuaikan dengan preferensi individu mahasiswa untuk menciptakan pengalaman belajar yang lebih menarik. Penelitian ini menggunakan pendekatan User-Centered Design (UCD) yang mengacu pada prinsip ISO 9241-210 untuk mengembangkan prototipe antarmuka UI high-fidelity. Evaluasi heuristik dilakukan oleh pakar untuk menilai kegunaan dan efektivitas desain. Temuan utama penelitian ini menyoroti bahwa elemen gamifikasi yang disesuaikan dengan preferensi MBTI dapat memenuhi kebutuhan pembelajar yang beragam dan meningkatkan interaksi dengan platform. Penelitian ini menunjukkan potensi gamifikasi berbasis MBTI sebagai strategi inovatif untuk pendidikan personalisasi. Penelitian lanjutan akan berfokus pada implementasi platform menjadi sistem fungsional serta pengembangan fitur untuk basis pengguna yang lebih luas.' WHERE id = 43750;

-- id=43753 source=openalex_title | Sugeno Fuzzy Personality Prediction System: An Approach to Overcoming Psychological Measur
UPDATE papers SET authors = 'Nadindra Dwi Ariyanta, Anik Nur Handayani', snippet = 'Personality prediction is a significant field in psychological measurement, yet it faces challenges due to psychological data''s ambiguous and uncertain nature. This study aims to develop a Sugeno-based fuzzy logic system for predicting personality types according to the Myers-Briggs Type Indicator (MBTI). The dataset includes synthetic personality data, incorporating age, introversion, sensing, thinking, and judging. The fuzzification process converts crisp input values into fuzzy variables, which are then processed using predefined fuzzy rules to generate personality predictions. The defuzzification step yields crisp outputs corresponding to MBTI types, demonstrating the system''s ability to handle uncertainty and ambiguity effectively. Implementation and evaluation were conducted using Python and LabVIEW, revealing a satisfactory performance with a low error rate of 0.445. This study highlights the potential of fuzzy logic, particularly the Sugeno method, in enhancing accuracy and adaptability in personality prediction, contributing to applications in education, human resource management, and personalized digital services.' WHERE id = 43753;

-- id=43757 source=openalex_doi | The New Adventure
UPDATE papers SET authors = 'Scott McIntosh, Tracy Cushing, Linda E. Keyes', snippet = 'To be a successful scholar in wilderness medicine, one must take risks. Just like reaching for the next handhold on a rock climb, descending deeper on SCUBA gear, or traveling to a far-off place to collect research samples from those of another culture, these risks challenge ourselves and define who we are. The past Editors of Wilderness and Environmental Medicine journal have all taken these steps. Paul Auerbach, Oswald Oelz, and William Robinson envisioned a medical field where none had been defined prior.' WHERE id = 43757;

-- id=43761 source=openalex_title | A Data-Driven Approach to MBTI Personality Classification: Insights from Machine Learning 
UPDATE papers SET authors = 'Fares A. Dael, Symbat Maidanova, Ibraheem Shayea, Gulnara Abitova, Aigul Seraly', snippet = 'The Myers-Briggs Type Indicator (MBTI) is one of the most widely recognized psychological tools for categorizing personality types, often used in various professional and personal development contexts. This study presents a data-driven approach to MBTI personality classification using a range of machine learning models. By leveraging a dataset comprising user responses and linguistic patterns, we aim to predict the MBTI personality types with greater accuracy and reliability. Various models, including Support Vector Machines (SVM), Random Forests, and Gradient Boosting Machines, were evaluated to determine their effectiveness in classifying the 16 MBTI types. Our findings reveal that machine learning models can significantly enhance the predictive accuracy of MBTI classification compared to traditional methods. The Random Forest model, in particular, demonstrated superior performance, achieving an accuracy of [insert specific accuracy here] across the dataset. We also explore the importance of feature selection and data preprocessing in improving model outcomes, highlighting key features that contribute to personality type prediction. The results of this study suggest that a data-driven approach, combined with machine learning techniques, provides a promising avenue for more nuanced and accurate MBTI personality assessments. This approach not only enhances our understanding of personality prediction but also offers practical implications for applications in psychology, human resources, and personal development.' WHERE id = 43761;

-- id=43765 source=openalex_title | The Relationship Between Students' Myers-Briggs Type Indicator and Their Behavior within E
UPDATE papers SET authors = 'Akerke Alseitova, Wilk Oliveira, Zhaoxing Li, Lei Shi, Juho Hamari', snippet = 'Leveraging user behavior has become an increasingly valuable resource for modeling and personalizing systems based on the unique characteristics of each user. While recent studies have recently been conducted along these lines, there is still a lack of understanding of the relationship between students’ Myers-Briggs Type Indicators and their behavior within educational systems. Facing this problem, we conducted a long-term study (15 weeks) with 96 students, analyzing how their engagement metrics and communication frequency in a Moodle Learning Management System are related to their Myers-Briggs personality types (i.e., extroversion/introversion, sensing/intuition, thinking/feeling, and judging/perceiving). The primary findings indicate that i) participants identified as extroverted demonstrated heightened activity levels throughout more weeks of the course, and ii) participants characterized by judging and thinking traits engaged in a greater number of activities over the course duration. The results contribute to the field of educational technologies by providing valuable insights into the relationships between different characteristics associated with the Myers-Briggs Type Indicator and students’ behavior when using an educational system.' WHERE id = 43765;

-- id=43768 source=openalex_doi | Comparative study exploring personality-communication correlation in design students and i
UPDATE papers SET authors = 'Mohana Das, Newman Lau, Wenjing Zhang, Kelly Tang, Dominic Y. H. Leung', snippet = '202502 bcch' WHERE id = 43768;

-- id=43769 source=openalex_title | MBTI Personality Type Prediction Using BERT-LSTM and Deep Learning on Social Media Posts
UPDATE papers SET authors = 'Veenu Rani, Chittireddy Akhil Reddy, V. Ramu, A. Ramesh Babu, Vallem Randheer Reddy, B Shruthi', snippet = 'It is well known that everyone has a particular ‘personality’ meaning a set of cognitive, affective, and behavioral characteristics. The current study uses text classification based on deep learning models i.e. BERT and LSTM, to predict user''s personality traits from their Facebook posts. With the Myers-Briggs type indicator (MBTI) as a baseline, the current research investigates the relationship between user-generated content and personality traits. The results reveal that such an architectural ensemble of BERT contextual embeddings with LSTM''s advantages over sequence data indeed results in higher accuracy over personality trait predictions than strategies like Naive Bayes and SVM machine learning algorithms. It was found that personality forecasting systems may benefit from the implementation of advanced NLP models, thus increasing the accuracy and usability of the systems, especially when targeting social media users.' WHERE id = 43769;

-- id=43771 source=openalex_title | Detection of Personality Traits Using Handwriting and Deep Learning
UPDATE papers SET authors = 'Daniel Gagiu, Dorin Șendrescu', snippet = 'A series of studies and research have shown the existence of a link between handwriting and a person’s personality traits. There are numerous fields that require a psychological assessment of individuals, where there is a need to determine personality traits in a faster and more efficient manner than that based on classic questionnaires or graphological analysis. The development of image processing and recognition algorithms based on machine learning and deep neural networks has led to a series of applications in the field of graphology. In the present study, a system for automatically extracting handwriting characteristics from written documents and correlating them with Myers–Briggs type indicator is implemented. The system has an architecture composed of three levels, the main level being formed by four convolutional neural networks. To train the networks, a database with different types of handwriting was created. The experimental results show an accuracy ranging between 89% and 96% for handwritten features’ recognition and results ranging between 83% and 91% in determining Myers–Briggs indicators.' WHERE id = 43771;

-- id=43772 source=openalex_title | Personalized Learning through MBTI Prediction: A Deep Learning Approach Integrated with Le
UPDATE papers SET authors = 'Samia Bousalem, Fouzia Benchikha, Naila Marir', snippet = 'Personalized e-learning systems have transformed the delivery of educational content, aligning it more closely with individual learners’ needs. Among the various approaches to achieving this personalization, the Myers-Briggs Type Indicator (MBTI) personality prediction emerged as a valuable tool for adapting learning content to match individual preferences and learning styles. Despite these advancements, personalized e-learning systems quite struggle with handling large volumes of information, often facing difficulties in balancing prediction accuracy and learning efficiency. To ensure personalization, integrating advanced technologies such as machine learning and deep learning is crucial for creating more sustainable and effective learning environments. This paper proposes a novel framework that integrates MBTI personality prediction with a deep learning approach and a Learner Profile ontology (LPO) to enhance the personalization and recommendation process. The proposed method employs the BERT model, a Transformer-based architecture, for personality prediction, combined with an oversampling technique to handle data imbalance. The predicted personality type is incorporated into a Semantic Web Rule Language (SWRL)-based ontology enriched with WordNet, enabling better alignment of learning resources with individual learner traits. Experimental results validate the efficacy of this integrated approach, demonstrating significant improvements in learner satisfaction and educational outcomes.' WHERE id = 43772;

-- id=43775 source=openalex_title | Improving resource choices for students and professionals in accounting and finance accord
UPDATE papers SET authors = 'Hisham Al Ghunaimi, Zalkha Ibrahim Ali Said Al Kharusi, Khoula Salim Ali ALBuwaiqi', snippet = 'This research investigates how personality traits, categorized by the Myers-Briggs Type Indicator (MBTI), influence the choice of learning resources among accounting and finance students and professionals. It evaluates the effects on skill enhancement and educational methodologies in the discipline. A preliminary study was carried out utilizing structured surveys to analyze the connection between personality types and preferred learning methods (such as books and online tools). This study offers initial results that establish a basis for more extensive research in the future. The findings reveal that 70% of participants saw a notable improvement in learning outcomes when their selected resources matched their MBTI personality types. The study highlights the significance of personalized resource selection in boosting understanding, efficiency, and professional advancement. Tailoring learning resources to align with personality traits leads to enhanced educational experiences and career growth. Nonetheless, challenges, including small sample sizes, need to be addressed in subsequent research. This research introduces an innovative framework that connects MBTI personality traits with ideal learning resources, providing practical recommendations for educators, students, and professionals to optimize learning efficacy and productivity in the fields of accounting and finance.' WHERE id = 43775;

-- id=43776 source=openalex_title | Personality preferences and stress perception among nursing students in different nursing 
UPDATE papers SET authors = 'Yuh‐Shiow Li, Hui‐Chen Tseng, Bao‐Huan Yang, Mary Etta Mills, Wen‐Pin Yu', snippet = 'BACKGROUND: Understanding personality preferences is crucial for guiding healthcare education and the stress management strategies of nursing students. While stress in nursing education has been well studied, its relationship with personality preferences, particularly in clinical settings, has been underexplored. This study aims to investigate the relationship between personality preferences and stress perception among nursing students in three different nursing programmes. METHODS: This cross-sectional study recruited 780 nursing students. We used structured questionnaires to collect data on demographics, personality preferences, and stress perception. The Myers-Briggs Type Indicator (MBTI) was used to measure personality preferences across four dimensions: extraversion/introversion, sensing/intuition, thinking/feeling, and judging/perceiving. The Chinese version of the MBTI and the Nurse Stress Checklist were also employed. Statistical analyses included descriptive statistics, one-way analysis of variance, and independent t-tests. RESULTS: Three common personality preferences were identified: extraversion, intuition, feeling, and perceiving; introversion, sensing, thinking, and judging; and introversion, sensing, feeling, and judging. The findings indicate that stress was significantly related to personality preferences. There were significant differences in the stress scores and the extraversion/introversion and thinking/feeling subscales. However, no significant differences in stress levels were observed across different nursing programmes. CONCLUSIONS: Each personality trait exhibited specific stress coping mechanisms. Addressing students'' stress is crucial because it can lead to academic burnout and attrition. This study''s findings can inform strategies to reduce stress while accommodating students'' personality traits, ultimately enhancing student success in nursing programmes.' WHERE id = 43776;

-- id=43778 source=openalex_title | Perbandingan Tree Based Model untuk Klasifikasi Tipe Kepribadian MBTI
UPDATE papers SET authors = 'Rani Asriya Effendy, Irving Vitra Paputungan', snippet = 'This study examines the use of Tree-Based Models for classifying Myers- Briggs Type Indicator (MBTI) personality types. Data was collected through questionnaires referencing the 16Personalities test, followed by preprocessing steps to handle missing values, split MBTI labels, and analyze statistical summaries. Seven algorithms, including Decision Tree, Random Forest, Extra Trees, and Gradient Boosting, were applied to evaluate classification accuracy across MBTI dimensions (E-I, S-N, T-F, J-P). Random Forest emerged as the best model with an accuracy of 72.5% when analyzing high-correlation questions, highlighting its robustness in managing data interactions. This research emphasizes the effectiveness of machine learning in personality classification and provides practical insights for integrating MBTI assessments into applications. Future work suggests leveraging larger, more diverse datasets and exploring deep learning integrations for enhanced model performance.' WHERE id = 43778;

-- id=43780 source=openalex_title | Research on English Language Teaching Based on Myers-Briggs Type Indicator Personality Mod
UPDATE papers SET authors = 'Tao Siru, Jia Jinyi, LI Jin-xia', snippet = 'Based on the Myers-Briggs Type Indicator (MBTI) as a theoretical framework, this study combines 313 valid questionnaires with mixed research methods (quantitative analysis and qualitative text mining) to systematically explore the differential effects of personality types on basic English literacy. Based on the cognitive load theory, social constructivism and task-based teaching methodology, this paper proposes a three-dimensional personality-strategy-resource model, and designs a differentiated teaching tool and a dynamic assessment mechanism to provide a new practical path and theoretical basis for the personalized reform of English teaching.' WHERE id = 43780;

-- id=43782 source=page_meta | A Brief Review on Language Learning Strategies and MBTI
UPDATE papers SET authors = 'Yangyang Gao', snippet = 'With the increasing popularity of the Myers-Briggs Type Indicator (MBTI) theory, various personality types defined by this framework are becoming more widely recognized and discussed. Upon identifying the different MBTI personality types, we can also explore how these types can be related to language learning strategies. In this field of study, we will...' WHERE id = 43782;

-- id=43791 source=openalex_doi | The Influence of Student Personality Traits on Satisfaction and Success in Online Educatio
UPDATE papers SET authors = 'Elizabeth G Hunter, Jayna Niblock, Samantha Barefoot, Jackson Miller, Jason Hughes, Lydia Kite, Edith Scarletto', snippet = 'Online learning is a growing area in occupational therapy education. It is important for faculty to use the modality of online learning to understand the influence of student personality traits, defined as relatively stable characteristics that influence thinking and behavior, on student satisfaction and success in graduate level programs. By understanding the influence of personality traits, faculty can better develop online materials that are flexible enough to support individuals who may have a higher risk of low satisfaction and success. There has been plentiful research in the areas of education and psychology assessing the influence of personality on the online learning experience. The goal of this systematic review was to collect, evaluate, and synthesize this literature to provide guidance to faculty working in or developing online courses or programs in occupational therapy. This systematic review was conducted according to the Cochrane Collaboration methodology and reporting is consistent with the PRISMA guidelines. The article search included January 2000 through June 2024. After duplicates were removed 848 articles remained, ultimately 99 were eligible for a full text review, and 23 were included in the three themes which were synthesized based on design and type of online education. The review highlights what is currently known related to the influence of personality type on online education. The information can be used to help sensitize educators to the influence different personality types can have when teaching online courses.' WHERE id = 43791;

-- id=43811 source=openalex_doi | Bending the rules of the game: Dark Entrepreneurship in a capitalist system
UPDATE papers SET authors = 'Gbemisola Ogbolu, Suzanne Hague', snippet = 'While the dream of success fuels many entrepreneurs, the realities of a competitive capitalist system can push some towards unethical ventures. The capitalist ideal celebrates innovation and wealth creation, however, the relentless pursuit of profit within this system can have a dark side: dark entrepreneurship. This chapter explores the phenomenon of individuals who engage in questionable business practices to achieve financial success, focusing on the ‘push factors’ inherent in capitalism that create a breeding ground for such activities. We analyse the complex relationship between dark entrepreneurs and the capitalist system and how the relentless pursuit of profit, coupled with factors like unemployment, limited access to resources, intense competition, and lax enforcement, incentivise entrepreneurs to bend the rules. While such behaviour can undermine ethical business practices and harm consumers, it can also expose weaknesses in regulations and highlight societal inequalities. Through real-world examples, the chapter considers the motivations and methods employed by dark entrepreneurs within a capitalist framework. We analyse how their actions highlight systemic weaknesses and contribute to a climate of distrust. While acknowledging the innovation potential that can emerge from some dark ventures, the chapter considers possible interventions, including strengthening legal frameworks, adopting a culture of ethical conduct, and ultimately, the need for reforms.' WHERE id = 43811;

-- id=43832 source=openalex_doi | Examining the dark personality traits of youth in the context of tourist visits to memoria
UPDATE papers SET authors = 'Metod Šuligoj, Tamara Jovanović', snippet = 'This positivist study elucidates the impact of the 1990s conflict and subclinical negative personality traits on the visits of young Serbians to memorial sites in the challenging post-conflict Balkans. Integrating collective memory, dark tourism, and dark personality traits, the study encompasses a homogeneous sample of 281 respondents within a multinational region, including Kosovo and Bosnia–Herzegovina as global hotspots. The often-neglected non-Western perspective is revealed by employing cross-tabulation with Fisher’s Exact Test and univariate and multivariate general linear modelling. The post-conflict generation, quite possibly experiencing ‘secondary traumatisation’, exhibits heightened vulnerability to narcissism and moderate interest in visiting memorial sites. Regardless of family exposure to conflict, the predominant reasons for visiting include learning, commemorating, and empathising, with no psychopathological links found. The study thus suggests that dark personality traits do not reliably predict visits to regional memorial sites, while the country of residence and the ability to understand one’s family do.' WHERE id = 43832;

-- id=43833 source=openalex_title | Analysis of Love of Money, Machiavellian on Ethical Knowledge and Ethical Perception of Ac
UPDATE papers SET authors = 'Rina Ani Sapariyah, Yenni Khristiana, Yuliani Eka Putri Prabandari, T. Husain', snippet = 'This study aims to analyze Love of Money and Machiavellian on the Ethical Perception of Accountant Behavior through Ethical Knowledge as an intervening variable. The sampling technique used was purposive sampling, and a sample of 100 respondents, calculated using the Slovin’ formula. This study used a questionnaire as a data collection method. Data analysis used to test the hypothesis was conducted by using the path analysis technique. This study obtained the results of the analysis that love of money had a positive and significant effect on ethical knowledge. Machiavellian had a negative but significant effect on ethical knowledge. This means that the ethical perception of accountant behavior is explained by love of money, Machiavellianism, and ethical knowledge by 70.9%, and the remaining 29.1% is explained by other variables outside the research model.' WHERE id = 43833;

-- id=43836 source=openalex_doi | Gen Z Hybristophilia: The Role of TikTok in Young Women's Attraction to Deviant Men
UPDATE papers SET authors = 'Emma Virginia Treggia, Μαρία Ιωάννου, Calli Tzani, David Lester, Lucas Rogers, Thomas James Vaughan Williams, John Synnott, Michelle Drouin', snippet = 'This research explores hybristophilia (an individual’s sexual interest in and attraction to those who commit crimes) among Generation Z women, particularly through investigating how Gen Z female users interact with and feel about hybristophilic content and how this content impacts their attraction to offenders. Study 1 involved a content analysis of 66 videos and 91 comments on TikTok, identifying seven main themes: The Halo Effect, Actor-Offender Transference, Sympathy, Romance and APD, Protection and Loyalty, “I Can Fix Him,” Gen Z Irony, and Victim Fantasy. Study 2 used a cross-sectional survey with 95 women aged 18–27 to measure exposure to and engagement with hybristophilic content, hybristophilia scores, dark personality traits, and empathy levels. The results indicate that participants’ engagement with hybristophilic TikTok content positively predicted their hybristophilia scores, which were also predicted by Machiavellianism and psychopathy. These findings highlight the need for targeted interventions to mitigate the influence of digital content on young women’s perceptions of offenders, addressing the influence of power dynamics associated with Machiavellianism and psychopathy. Moreover, they provide a solid foundation for future research and clinical practice regarding hybristophilia, with the proposed Hybristophilia Scale being a promising tool for use in clinical settings upon further validation.' WHERE id = 43836;

-- id=43843 source=openalex_doi | A Mach's Match: How CEO Machiavellianism Impacts Cross-Border Acquisitions
UPDATE papers SET authors = 'Mithira Siva, Sumit Chakraborty', snippet = 'This study investigates the impact of CEO Machiavellianism on cross-border acquisitions (CBAs), addressing a critical gap in the literature on leadership traits and their impact on CBA decisions. Specifically, drawing on the upper echelons theory and the psychology literature, we explore how CEO Machiavellianism impacts the number of CBA deals that a firm initiates in a given year. Further, we examine how CEO tenure and CEO gender work as important boundary conditions for the above relationship. Empirical analysis based on 4034 firm-year observations from S&P 1500 firms support our theoretical predictions, revealing that Machiavellianism increases the number of CBAs during shorter tenures but decreases it as tenure lengthens. Additionally, Machiavellianism is linked to a higher number of CBAs for female CEOs and a lower number for male CEOs. These findings extend upper echelons theory by highlighting the critical roles of tenure and gender in influencing the strategic effects of CEO personality traits, offering valuable insights for scholars and practitioners.' WHERE id = 43843;

-- id=43845 source=openalex_doi | When the Underdog Speaks: How Low-Performing Employees Voice Impacts Leaders Trust and Emp
UPDATE papers SET authors = 'Sihong Huang, Li Hu', snippet = 'Extant research has generally assumed that ideas or opinions expressed by high-performing employees are more likely to arouse leaders’ attention and elicit positive responses from leaders. Drawing upon costly signaling theory, we challenge this prevailing assumption by exploring how and when low-performing employees’ voices can bring benefits for them. We propose that the voice of low-performing employees is more likely to enhance leaders’ trust in these employees, which in turn promotes leaders’ empowering behaviors. We further consider the moderating role of leader Machiavellianism in these relationships. We found support for our hypotheses across an experiment and a field study. Results showed that employee voice was positively related to leader trust and subsequent empowering behavior when employee task performance was low. Moreover, the results revealed an important three-way interaction effect. Only when both employee task performance and leader Machiavellianism were low, did employee voice positively influence leader trust and subsequent empowering behavior. Taken together, our findings reveal the benefits of low-performing employees’ voices for themselves and the importance of encouraging low-performing employees to speak up in the workplace.' WHERE id = 43845;

-- id=43848 source=openalex_doi | Divine Influence: Investigating Whether Leader Religiosity & Self-Efficacy Spur Dark Dyad 
UPDATE papers SET authors = 'Sajida Hafeez', snippet = 'This study emphasizes the significant role of leader religiosity in shaping employee outcomes, particularly in the context of dark dyad traits (Machiavellianism and psychopathy) and job performance, drawing on social cognitive theory. We propose and test a model that highlights how leader religiosity moderates the influence of these dark traits on employee performance, both directly and through self-efficacy. Addressing a gap in the literature, we utilize a multi-wave, multi-source dataset from 506 employees and 81 managers across 29 service-oriented companies in Pakistan to support our hypotheses. The findings reveal a positive link between Machiavellianism and self-efficacy, which enhances job performance, while the negative relationship between psychopathy and self-efficacy is significantly moderated by leader religiosity. To further validate these results, a second experimental study using a 2x2 factorial design confirms that leader religiosity mitigates the negative behaviors associated with dark dyad traits and boosts employee self-efficacy and performance. Overall, this study underscores the potential of leader religiosity to improve employee outcomes in organizational settings by moderating the impact of dark traits.' WHERE id = 43848;

-- id=43852 source=openalex_doi | The Freedom Fallacy: A Structuration Approach to Autonomy in New Venture Teams
UPDATE papers SET authors = 'Katrina M. Brownell, Jill Kickul, Denis A. Grégoire', snippet = 'Autonomy is considered vital to entrepreneurship, but in the context of a new venture team (NVT), excessive independence in individual team members could disrupt the collective processes necessary for coordinated action. Drawing on structuration theory, we reconceptualize autonomy as a dynamic force that both shapes action and is shaped by the structure of a NVT. Using time-lagged data across two studies (N = 46, 62 teams), we find that autonomy in team members has an inverted U-shaped curvilinear relationship with innovation. Moreover, we demonstrate that certain lead founder personality traits – Machiavellianism, narcissism, and psychopathy – create “structuration contexts” that shape how autonomy enables or constrains innovation. Theoretical contributions, practical implications, and promising avenues for future research are discussed.' WHERE id = 43852;

-- id=43855 source=openalex_title | Cyberpsychopathy: A Multidimensional Framework for Understanding Psychopathic Traits in Di
UPDATE papers SET authors = 'Alexandre Hudon, Emmy Harvey, Sandrine Nicolas, Mathieu Dufour, Caroline Guérin-Thériault, Julie Bérubé-Fortin, Isabelle Combey, Yu Chen Yue, Antoine Perreault, Stéphanie Borduas Pagé, Véronique MacDermott', snippet = 'The rapid expansion of digital communication platforms has created new spaces for antisocial, manipulative, and emotionally detached behaviors. While psychopathy has been extensively studied in clinical and forensic settings, its digital manifestation, referred to as cyberpsychopathy, remains conceptually underdefined. This integrative review aimed to synthesize empirical research exploring psychopathy and aversive personality traits in online contexts to identify key conceptual domains and propose a preliminary definition. A systematic search across five databases yielded 35 peer-reviewed studies meeting the inclusion criteria. Using a biopsychosocial framework and thematic synthesis, six interrelated domains were identified: online behaviors (e.g., trolling and deception), online environments (e.g., anonymity and reward mechanisms), sociodemographic factors (e.g., age and gender), personality traits (e.g., psychopathy and narcissism), psychological factors (e.g., emotion dysregulation and low self-esteem), and motivations (e.g., dominance and emotional compensation). These domains interact to shape how psychopathic tendencies manifest online. Most studies were of moderate-to-high methodological quality, though variability limited direct comparisons. We propose cyberpsychopathy as a multidimensional construct representing the expression of aversive traits facilitated by digital affordances and psychological vulnerabilities. This review provides a foundational framework for understanding cyberpsychopathy and underscores the need for empirical validation and the development of assessment tools suited to digital behavior in both clinical and forensic settings.' WHERE id = 43855;

-- id=43860 source=openalex_title | The Role of Dark Personality Traits in Shaping Bystander Behavior to Cyberbullying Among a
UPDATE papers SET authors = 'Habib ur Rehman, Muhammad Waseem Iqbal Awan, Laiq Hussain', snippet = 'Cyberbullying is defined as a type of bullying that has been experienced in recent years and involves the use of electronic media to threaten or harass others. This systematic review aims to review the literature on the effect of dark personality traits such as Machiavellianism, Narcissism, Psychopathy, and Sadism on bystander behavior in cyberbullying among adults. Among the databases searched, including PsycARTICLES, PubMed, IEEE Xplore, Scopus, and Google Scholar, the publications from 2010 to 2024 were selected, and 52 articles were included in this study. The review indicates that dark personality traits affect bystander behavior since they lead to inaction and encourage passive or acquiescent behavior. In particular, narcissists will not act unless there are personal social returns to bullying, whereas psychopaths are either apathetic or proactive in bullying. Machiavellians will likely analyze the circumstances and become involved only when it benefits them. In contrast, sadists are likely to increase the level of bullying to gain pleasure from other people’s suffering. Empathy training, a decrease in anonymity, and platform-specific regulation are suggested to combat these influences. The review also points to the gaps, including the lack of cross-cultural comparisons, longitudinal data, and randomized controlled trials to determine causality. Putting together psychophysiological data and looking at the overall effects of interventions can help us figure out how the bystander''s choice is made in terms of thought and emotion.' WHERE id = 43860;

-- id=43871 source=openalex_title | The impact of personality traits and the mediating role of self-efficacy and self-control 
UPDATE papers SET authors = 'Cornelia Rada, M Ramendik Dina, Robert-Andrei Lunga', snippet = 'The study aimed to evaluate the possible mediating effect of two independent variables, self-efficacy and self-control, and to analyse the role of personality traits in the manifestation of criminogenic behavior. A total of 850 detainees from Romania, aged between 21 and 71 years (mean age = 38.7; standard deviation = 10.58), completed the CP5F Personality Questionnaire, the Criminogenic Cognitions Scale (SCC), the Machiavellianism Scale, and the Self-Efficacy Scale. The mediation model showed the following. Self-efficacy and self-control parallelly mediate the relationship between personality (p < 0.05) and the negative attitude toward the individual/authority (p < 0.01). As the score for self-efficacy increases, the score for Machiavellianism and the score for the negative attitude toward the individual also increase. As the score of self-control increases, the score for Machiavellianism decreases. The personality score explains approximately 27% of the variance in the self-efficacy score and 7.2% of the variance in the self-control score (p < 0.001). Self-control and self-efficacy are psychological dimensions that must be developed from adolescence, but in the direction of desirable, prosocial behaviours to prevent the formation of a criminal identity. Strengthening personality factors (Extraversion, Agreeableness, Conscientiousness, Emotional Stability, and Autonomy) can lead to a decrease in negative attitudes toward authority and the individual, which can result in a decrease in recidivism.' WHERE id = 43871;

-- id=43873 source=openalex_doi | An Integrative Approach to the Prediction of Argumentativeness
UPDATE papers SET authors = 'Stephen M. Croucher, Stephanie Kelly, Lenis Aislinn C. Separa, Tommy S. Yotes, Zhidan Zhou, Ranjeeta Singh, Douglas Ashwell, Shawn M. Condon', snippet = 'This study explored the extent to which demographics (age and level of education), the “Big Three,” (extraversion, neuroticism, and psychoticism), cognitive dispositions (locus of control and resilience), and social personal dispositions (Machiavellianism) combine to predict argumentativeness. Based on a representative sample of 877 participants from the United States, the results revealed that when taken together, previously established effects of some of these variables on attitude toward arguing are verified, although some are not consistent. Level of education and locus of control did not affect attitude toward approaching an argument as in the previous research. Implications for future research are discussed, with an emphasis on future research taking a more comprehensive approach to the study of communication.' WHERE id = 43873;

-- id=43880 source=openalex_doi | Assessing Workplace Social, Emotional, and Behavioral Skills in Africa
UPDATE papers SET authors = 'Vic Marsh, Clara Delavallade, Smita Das, Léa Rouanet, Tricia Koroknay-Palicz, Dawn McDaniel', snippet = 'Social, emotional, and behavioral skills are critical for success across life domains, yet research is constrained by a lack of internationally validated measures for adult populations. Existing tools often assess isolated skills and are predominantly validated in Western, school- aged samples. To address these limitations, this study developed and validated the Effective Socio-emotional skills To gain Economic EMpowerment framework, comprising 14 distinct social, emotional, and behavioral skills with prior demonstrated relevance to economic outcomes. The framework’s self-report scales were tested among adults in six Sub-Saharan African countries (Côte d’Ivoire, Nigeria, the Republic of Congo, Rwanda, South Africa, and Tanzania), spanning diverse cultural and linguistic contexts (English, French, Hausa, Swahili, and Yoruba). The results confirm the psychometric validity of the scales, supporting their utility in both research and practice. The framework categorizes skills as intrapersonal or interpersonal, awareness or management, and agentic or communal, providing a robust tool to unpack which skills matter for employment and earnings and how this differs by gender. By enabling exploration of social, emotional, and behavioral skills in underrepresented and cross-cultural contexts, use of the Effective Socio-emotional skills To gain Economic EMpowerment self-report scales advances theoretical and practical understanding of social, emotional, and behavioral skills in adult populations.' WHERE id = 43880;

-- id=43883 source=openalex_title | Bridging the gaps: abusive supervision, retaliation behavior, religious faith, Machiavelli
UPDATE papers SET authors = 'Hina Yaqub Bhatti, Ayesha Zahid, Shazia Nauman, Nida Usman Jahangir', snippet = 'Purpose This study investigated the process linking abusive supervision and affective commitment by examining the mediating role of retaliatory behavior. It also examines the moderating roles of religious faith and Machiavellian personality. Design/methodology/approach A two-wave time-lagged survey was conducted with 215 working professionals. Abusive supervision and retaliatory behavior were measured at Time 1. Religious faith, Machiavellian personality and affective commitment were measured at Time 2. Findings Results indicate partial mediation of retaliatory behavior in abusive supervision—affective commitment relationship. Furthermore, faith attenuates abusive supervision thus mitigating employees’ retaliatory behavior. Moreover, Machiavellian personality intensifies the harmful effects of abusive supervision on employees’ retaliatory behavior. Practical implications Organizations should implement policies to restrain abusive supervision and train supervisors to mitigate its harmful effects. Religious inclusivity may restrain retaliation. Screening for Machiavellian personality may reduce its exacerbating influence. Furthermore, organizations can empower employees by involving them in collaborative goal-setting and decision-making. Originality/value This study examines retaliation behavior as an underlying mechanism and introduces religious faith and Machiavellian personality as moderators in an under-researched Pakistan developing country context.' WHERE id = 43883;

-- id=43884 source=openalex_doi | Are the Links Between Dark Traits of Personality and Violent Attitudes Mediated by a Prope
UPDATE papers SET authors = 'Pedro Pechorro, Kevin L. Nunes, Victor H. Palma, Bruno Bonfá-Araújo, Matt DeLisi', snippet = 'The current study examined moral disengagement mediation effects related to the dark traits of personality – the Dark Core and the Dark Tetrad composed of Machiavellianism, narcissism, psychopathy, and sadism – and violent attitude links. The sample consisted of 354 participants (M = 32.02 years, SD = 13.26 years) from economically and socially deprived areas in the south of Portugal. Mediation analysis employing path analysis statistical procedures mostly indicated that moral disengagement partially mediates the relations between the dark traits of personality – Dark Core and Dark Tetrad – predictors and the violent attitudes outcome. The exception was the narcissism factor of the Dark Tetrad, which presented non-significant mediation results. Cognitive mechanisms, such as moral disengagement, can act as mediators between dark personality traits and violent attitudes. These results underscore the importance of considering the multifaceted nature of dark personality traits when associating it with complex outcomes, such as violent attitudes.' WHERE id = 43884;

-- id=43895 source=openalex_doi | Navigating the Dark Side of Leadership: Insights from Nigeria's Public Sector
UPDATE papers SET authors = 'Sheriff Folarin, U. D. Abasilim, Mostafa M. Jalal', snippet = 'It is established that dark leadership impairs organisational integrity, erodes public trust, and diminishes operational effectiveness. The chapter reviews the endemic problem of dark leadership in the public sector, its manifestations, consequences, and lessons for leaders. Identifiable practices of public institutions are leveraged to discuss the negative implications of unethical attributions on organisational functioning. It identifies upholding ethical standards, fostering transparency, and ensuring robust accountability as mitigation measures against the risk of unethical behaviour. The chapter advocates a culture of integrity, continuous ethics and compliance training, protection for whistleblowers, and optimal internal controls are essential in sustaining ethical leadership. The insights provided are notable for a cross-section of leaders to achieve effective governance and resilient institutions.' WHERE id = 43895;

-- id=43897 source=openalex_title | Chief executive officer (CEO) Machiavellianism and executive pay.
UPDATE papers SET authors = 'Tessa Recendes, Aaron Hill, Federico Aime, Jason W. Ridge, Oleg V. Petrenko', snippet = 'Integrating theory and evidence about Machiavellianism (Mach) into executive pay-setting research, we theorize about how chief executive officers (CEOs) higher in Mach may be both more motivated to initiate negotiations and more effective in utilizing social influence tactics in the pay-setting process, thus positively relating to their own pay outcomes. Specifically, we first theorize that CEO Mach positively associates with a CEO''s total pay and severance pay. Moreover, because paying top management team (TMT) members more is also in CEOs'' interests-such as to help build TMT loyalty and cooperation, aid hiring, and ease retention while also narrowing the CEO-TMT pay differential to thus provide an impetus for a CEO pay raise-we argue that CEO Mach positively relates to TMT pay as well. Using a longitudinal sample of S&P 500 firms and clinical psychologists trained to assess CEO Mach from publicly available data, we find evidence supporting our theorizing. (PsycInfo Database Record (c) 2025 APA, all rights reserved).' WHERE id = 43897;

-- id=43898 source=openalex_doi | The individual and situational factors predicting unethical behaviour in the workplace: a 
UPDATE papers SET authors = 'Thomas Rhys Evans, James E. Bartlett, Amélie Gourdon-Kanhukamwe, Tim Allen, Georgia Antoniou, Sara Arent, Dea Resta Cicilia Asmarani, Neelo Binns, Clara Boulton, Joshua Bowhay, Linnea Cederlund, Ramnik Chana, Y.Y. Chou, Kevina Dookheea, Gurbani Guglani, Abi Hamson-Ford, Holly Hood, Eci Balim Hostafci, Suha Jahanzeb, Kaylie Webb-Jones, Gemma Katie M Joseph, Tephilla Kemalesh, Lamiss-Roya Karoui, Soha Khan, Renata Kviatkoyskyte, Jing Xuan Lee, Rahimah Lewis, Odelia Logan, Georgia A. Martin, Samaneh Vahedi Moghadam Masuleh, Rebecca McCulloch, Pragya Modi, Susan Nakro, Vy H. Nguyen, Minh Q. Phan, Edward Philcox, Ana B Pliego, Sasha Raman, Anusha V. Ramji, Anna M. H. Ramsay, Natasha E Rhone-Parkinson, Tayla Rizzo-Powell, Attila Simony, Roksana A Sobolak, Maia Thompson, Believe Ujobundo, Bhagyashree Vijayakumar, Natalja Wells-Dean, Michaela Natasha Wernick, Gemma Wood, Chan Young Yang, Zareen Zahid, Colleen Addicott, Hazel Bending, Elisabeth E.F. Bradford, Peter Branney, Joanna Butler, Irene Chu, Oliver J. Clark, Laura A. Dean, Yannick Griep, Tom Hatton, Caroline Heard, Olivia S. Kowalczyk, Alexandra Lautarescu, Tony McCarthy, Kimberly R. More, John S. Sabo, Joyce Elena Schleu, Dora Scholarios, Rosalind Searle, Ilham Sebah, Laura Wallis, Ruijie Wang, Jérémy E. Wilson-Lemoine, Emma Wilson-Lemoine, Calvin Burns', snippet = 'Intentions to act unethically in the workplace are purported to be driven by a number of situational and individual factors. Across two seminal vignette experiments, Jones and Kavanagh reported inconsistent effect sizes for manager and peer influence and locus of control, consistent significant effects for work quality and Machiavellianism, and consistent non-significant effects for gender. Using an innovative multi-site collaboration, the current Registered Report represents a direct replication of these experiments (N = 2218), and adds a longitudinal conceptual replication capturing self-reported unethical work behaviour (N = 1747). Both replications found a consistent small effect of having a more external locus of control and male identity, and a consistent moderate effect of machiavellianism, for increasing unethical intentions and behaviour. The situational factors, whilst consistent in direction with that of the original study, varied more substantively in effect size. Our results highlight the value of multi-site collaborations and different replication types in developing conceptual, methodological, measurement and theoretical clarity to ensure future works can progress more rapidly to minimize the negative impacts of unethical workplace behaviour and improve individual’s working lives. All materials, code and data for this project can be found here: osf.io/d3arx.' WHERE id = 43898;

-- id=43899 source=openalex_title | Longitudinal impact of machiavellianism on adolescent prosocial behavior and suicidal risk
UPDATE papers SET authors = 'Kaixuan Gao, Fengling Fang', snippet = 'BACKGROUND: Adolescence represents a pivotal stage marked by substantial physiological and psychological transformations, during which prosocial behavior and suicide risk are of paramount concern. Machiavellianism, a personality trait encompassing self-centeredness, utilitarianism, and manipulativeness, may exert an influence on these behaviors. This study was designed to explore the impact of Machiavellianism on adolescent prosocial behavior and suicide risk, with a specific emphasis on the mediating effects of hope and loneliness. METHODS: A sample of 618 Chinese middle school students (mean age: 13.65 years) participated in this study by completing assessments of Machiavellianism, hope, loneliness, prosocial behavior, and suicide risk at two distinct time points. Structural equation modeling techniques were utilized to investigate the mediating roles of hope and loneliness. RESULTS: The findings revealed a negative correlation between Machiavellianism and prosocial behavior, as well as hope, while a positive association was observed between Machiavellianism and loneliness and suicide risk. Furthermore, hope and loneliness emerged as mediators in the relationship between Machiavellianism and both prosocial behavior and suicide risk, with hope functioning as a protective factor and loneliness serving as a risk factor. CONCLUSION: The study offers valuable insights into the intricate interplay among Machiavellianism, hope, loneliness, prosocial behavior, and suicide risk in adolescents. Understanding these intricate relationships can guide the development of targeted mental health interventions aimed at addressing the needs of high-risk youth.' WHERE id = 43899;

-- id=43905 source=openalex_title | Fear is the path to the dark side: the interplay of leader fear of power loss and leader M
UPDATE papers SET authors = 'Diana Rus, Ed Sleebos, Barbara Wisse', snippet = 'Purpose While leaders value power for its material, social, and psychological benefits, it remains fragile and easily lost. We propose that leaders who fear losing power are driven to protect it, potentially resorting to abusive supervision to reaffirm their authority. Furthermore, we argue that this tendency should be especially pronounced among leaders high in Machiavellianism. Thus, we examine the joint effects of leader fear of power loss and Machiavellianism on abusive supervision. Design/methodology/approach We employed a multi-study design, starting with a business scenario experiment involving 365 leaders, followed by a multi-source field study among 546 leaders and 1,718 subordinates. Findings Both studies consistently showed that leader fear of power loss is positively related to abusive supervision, with this effect strengthening as leader Machiavellianism increases. Practical implications To curb antinormative behaviors like abusive supervision, organizations can strengthen leaders’ sense of safety in their positions, factor Machiavellianism into selection and promotion decisions and implement (in)formal mechanisms to limit its expression. Originality/value Our work underscores the importance of studying leader fear of power loss, an underexplored research area. By focusing on leader Machiavellianism, it also increases our understanding of when leader fear of power loss may result in destructive behaviors.' WHERE id = 43905;

-- id=43906 source=openalex_doi | Pocock and Meinecke, Machiavellianism and Historicism
UPDATE papers SET authors = 'Brian Young', snippet = 's centenary but also that of the publication of Friedrich Meinecke''s classic study of Machiavellianism; a critical assessment of the relationship between the two historians and students of historiography is, therefore, timely.As early as 1957, Pocock referred to the ''disasters'' associated with the rise of historicism; implicit in this assertion is the history of antisemitism within German intellectual life,' WHERE id = 43906;

-- id=43908 source=openalex_title | Effects of Fraud Risk Indicators and Machiavellianism on Auditors' Risk Assessment
UPDATE papers SET authors = 'R. Douglas Parker, Douglas M. Boyle', snippet = 'ABSTRACT Audit standards require auditors to assess fraud risk and maintain professional skepticism (PS) throughout an audit engagement (American Institute of Certified Public Accountants (AICPA) 2019a). Our study investigates the effects of Machiavellianism (high/low) and fraud risk indicators (high/low) on fraud risk assessment. Specifically, 118 experienced auditors assessed fraud risk in a 2 × 2 experiment where Machiavellianism was measured, and fraud risk indicators were manipulated between subjects. Building on trait activation theory, which indicates underlying personality traits will be activated based on task or situational cues, we predicate, and results imply, that auditors with higher Machiavellian traits assess fraud risk significantly higher when fraud risk indicators are low. These results have important implications, as research has shown that an auditor’s initial fraud risk assessment influences the level of skepticism throughout an audit engagement. Data Availability: Contact the first author for more information.' WHERE id = 43908;

-- id=43925 source=openalex_title | Social–Psychological Underpinning of Anti–Church Sentiment
UPDATE papers SET authors = 'Zlatko Šram', snippet = 'The aim of this research is to learn whether social alienation, Schwartz’s values, psychopathy, and Machiavellianism contribute to the prediction of results obtained on the scale of anti–Church sentiment. The survey was conducted on a convenience sample of full–aged citizens of Croatian ethnicity. Factor analysis was performed on the scales of anti–Church sentiment, social alienation, and Schwartz’s 10 individual values in order to establish the construct validity of these measurements. The results of the first multiple regression analysis revealed that social alienation and value orientations were significant predictors of anti–Church sentiment. The second multiple regression showed that primary psychopathy and Machiavellianism were also significant predictors of anti–Church sentiment. The construct of anti–Church sentiment was proven to be a hybrid of personal and attitudinal variables and motivated social cognition. Factor analysis performed was based on all variables investigated, and it revealed the existence of a latent “dark” attitudinal–personal construct of which anti–Church sentiment is a factorially significant component. Such a construct of anti–Church sentiment implicates the existence of a personality disorder and social dysfunction, and, at the same time, indirectly implies alienation or estrangement from the life of God.' WHERE id = 43925;

