-- export (6) v2 chunk 001 — 13 updates

-- id=45210 source=page_meta | Social Media Addiction: An Unrecognized Yet Pervasive
UPDATE papers SET authors = 'Yibo Wang', snippet = 'This research paper focuses on the lack of attention to social media addiction (SMA), the stigmatization of SMA, and data on the stigmatization of groups of people with high or low risk of SMA collected through a survey based on the Big Five Aspects Scales (BFAS) and Bergen Social Media Addiction Scale (BSMAS). T-tests of the data show relations between...' WHERE id = 45210;

-- id=45213 source=page_meta | Determining associations between Big Five personality traits and executive function in an 
UPDATE papers SET authors = 'Emma Quarles, Samuel J. West, Larry Keen', snippet = 'ObjectiveThe present study sought to determine the associations between executive functioning and Big Five personality traits in an undergraduate sample.Method:Participants included 200 undergraduates (73% women), with a mean age of approximately 21 years. Participants completed the Big Five Inventory-44 and a psychological assessment battery, which included the Trail Making Test and the Semantic Fluency Test.Results:Results from multiple regression analyses suggested agreeableness was negatively associated with Semantic Fluency – Animals (β = −0.310, p &amp;lt; 0.001). Moreover, conscientiousness was positively associated with Trail Making Test B-A (β = 0.197, p = 0.016), but negatively associated with Trail Making Test A (β = −0.193, p = 0.017).Conclusions:Overall results identified that executive function association with personality varies by construct. Given conscientiousness’ differential associations within the executive function task performances, future research should examine the conscientious threshold that would result in psychological symptomatology associated with extreme lows and highs in conscientiousness.' WHERE id = 45213;

-- id=45230 source=page_meta | Personal Traits and Motivation Impact on Collectibles as an Alternative Investment: A Case
UPDATE papers SET authors = 'Aldrich Aryadi, Margaretha Lingga', snippet = 'Collecting is a unique economic behavior that bridges pure consumption and investment, shaped by many psychological factors. This study examines how personality traits and motivations impact the decision to invest in collectibles, with a particular focus on Trading Card Game (TCG) collectibles. Previous research has explored how personality and motivation...' WHERE id = 45230;

-- id=45237 source=page_meta | Kontribusi Perilaku Tipe A, Neurotisme, dan Ekspektasi Terhadap Burnout Syndrome pada Pera
UPDATE papers SET authors = 'Shofiyah Karimah, Imam Subekti, Naya Ernawati, Tri Johan Agus Yuswanto', snippet = 'Kontribusi Perilaku Tipe A, Neurotisme, dan Ekspektasi Terhadap Burnout Syndrome pada Perawat di Kamar Operasi' WHERE id = 45237;

-- id=45282 source=page_meta | Changes in Plant-Herbivore Interactions Across Time Scales: Bridging Paleoecology and Cont
UPDATE papers SET authors = 'Adroit, Benjamin, Kozlov, Mikhail V., Robledo, J. Manuel  Manuel, Schachat, Sandra R.', snippet = 'Plants and arthropods predominate in terrestrial ecosystems, both in biodiversity andbiomass (Bar-On et al., 2018). Their trophic interactions, primarily herbivory, haveprofoundly shaped terrestrial ecosystems, affecting evolutionary trajectories, ecosystemstructures, and responses to environmental change. The fossil record provides key insightsinto long-term processes and large-scale patterns of arthropod (mainly insect) herbivorystretching back to early terrestrial ecosystems, such as the Silurian (~443-419 million yearsago) and Devonian (~419-359 million years ago) (Labandeira and Wappler, 2023), despitelimitations from temporal and spatial gaps and the need to deduce ecological patterns basedon insect morphology, community composition, and plant damage caused by herbivores.Contemporary ecology, in contrast, allows for direct real-time observation and precisemeasurement of variables related to herbivory, though it lacks the expansive temporal scope.Ideally, our understanding of plant–insect interactions would integrate insights fromboth ancient and modern ecosystems, spanning ecological (particularly macroecological) andevolutionary patterns across geologic timescales and present-day contexts, with implicationsfor the future. The five manuscripts in this special issue contain a multitude of paleoecological insights that will interest specialists in both ancient and modern ecosystems.A plurality of evidence of Paleozoic insect herbivory comes from the Permian of Texas. The frequency and richness of herbivory on Permian ferns and gymnosperms is lower than what we typically see in much younger, angiosperm-dominated deposits, but nevertheless varies considerably (Labandeira andAllen 2007, Schachat et al. 2014). Dos Santos et al. break new ground with the first report of Permian herbivory that includes feeding event occurrences, an exceptionally finely resolved form of data (Xiao et al., 2022). Dos Santos et al. found a low proportion of herbivorized surface area,…' WHERE id = 45282;

-- id=45285 source=page_meta | The Big Five Personality Traits and Eating Habits among Female Students at Zayed Universit
UPDATE papers SET authors = 'AlBlooshi, Sharifa, AlSabbah, Kawther, Thani, Shatha, Hijazi, Rafiq, Al Dhaheri, Ayesha S.  S., Zeb, Falak, Cheikh Ismail, Leila', snippet = 'BackgroundAdhering to healthy dietary habits is crucial for disease prevention and improving overall quality of life. Understanding how personality traits influence eating behaviors is essential for developing effective interventions aimed at promoting healthier eating habits. Personality traits are consistent behavioral patterns that individuals typically exhibit, and the Five-Factor Model (also known as the Big Five) is widely recognized as an effective framework for predicting personality traits.MethodsThis study analyzed the relationship between personality traits and eating behaviors among 425 female students using a cross-sectional design. Sociodemographic data and personality traits were assessed using an online questionnaire, while eating behaviors were evaluated with the validated Three-Factor Eating Questionnaire (TFEQ). Key aspects of eating behavior studied included cognitive restraint, disinhibition, and emotional eating. The findings provide insights into how personality characteristics may influence eating habits, offering potential implications for interventions targeting healthier eating behaviors.ResultsThe majority of participants scored highest on the personality trait of openness to experience. The study found that certain personality traits, particularly neuroticism and agreeableness, were linked to dietary habits. Specifically, personality traits were associated with emotional eating (p < 0.003), but not with cognitive restraint (p = 0.25) or disinhibition (p = 0.308). Participants with higher levels of agreeableness demonstrated significantly higher cognitive restraint (p = 0.041).ConclusionPersonality traits can influence eating habits, particularly emotional eating. However, further research is needed to identify individuals at risk for diet-related diseases and to determine the most effective intervention strategies. This study is the first of its kind conducted in the United Arab Emirates, contributing valuable insights into the…' WHERE id = 45285;

-- id=45297 source=semantic_scholar_title | Analisis Dampak Perbedaan Tipe Kepribadian Pasangan Terhadap Penyebab Fenomena Perceraian 
UPDATE papers SET authors = 'Tri Utami Febriyani, Mirna Nur Alia Abdullah', snippet = 'The phenomenon of young divorce due to differences in the personality types of couples as a determinant of differences in the perspective and life values of couples is a significant factor in the phenomenon of young divorce in our country. It is necessary to analyze the impact of differences in the personality types of couples on the phenomenon of young divorce, and of course it is also important to explain other factors that can affect the relationship of couples. Such as poor communication levels, an imbalance of abilities, or limited skills in conflict control, can all exacerbate the effects of personality type differences. Therefore, it is important for young couples to develop all the potential changes they have to achieve equality and harmony in their relationship through effective communication skills. In this research, a common writing method is used, namely Literature Review. The results of the research discussion of this literature review article contain an Analysis of the Impact of Differences in Spouse Personality Types on the Causes of the Young Age Divorce Phenomenon, namely the existence of a mismatch in the communication style between spouses can cause various misconception problems that can lead to divorce. Suggestions that researchers can give are the need for a more exclusive pre-marital teaching about the types of personality of couples and teaching how to manage the differences that occur between couples.' WHERE id = 45297;

-- id=45300 source=page_meta | OCC-PAD-OCEAN: An Quantitative Perceptible Modeling of Big Five Personality Based on Compu
UPDATE papers SET authors = 'Liu, Feng, Hu, Jingyi, Zheng, Qijian', snippet = 'In the field of human-centred artificial intelligence, there is an increasing focus on the development of AI systems that can be interpreted and quantified from a psychological perspective. This study represents an interdisciplinary fusion of computer science and psychology, with the objective of revolutionising the analysis of personality traits through the application of deep learning techniques. Our research is based on the ''OCC-PAD-OCEAN'' approach and employs the robust VGG19 deep learning architecture for the analysis of video data. The error rate of the AI-generated personality prediction is approximately 20% in comparison to the results obtained from the Big Five personality questionnaire. The empirical findings indicate that the predicted values of C (P < 0.001), E (P = 0.005), and A (P = 0.029) dimensions exhibit a significant difference from the measured values (p > 0.05), thereby demonstrating the model''s capacity to accurately reflect subtle individual differences within the Big Five traits. It is noteworthy that our analysis revealed minimal gender-related variations (p = 0.611, p = 0.828, p = 0.522, p = 0.696, p = 0.806), yet notable age-related distinctions in traits such as Agreeableness and Neuroticism (p = 0.027 and p = 0.025). The ''OCC-PAD-OCEAN'' approach not only overcomes the inherent limitations of traditional questionnaires by providing a more accurate and computationally efficient alternative for psychological evaluations, but also demonstrates the transformative potential of integrating deep learning into psychological analyses.' WHERE id = 45300;

-- id=45301 source=page_meta | The Effects of Personality Traits on Learning Engagement among College Students: The Media
UPDATE papers SET authors = 'Dang, Tongtong, Du, Wenxiu, Niu, Menghui, Xu, Zhenguo', snippet = 'IntroductionAs we all know, learning engagement is a key indicator for measuring the quality of students’ learning outcome and assessing their learning effectiveness. However, the relationship among personality traits, emotion regulation, and learning engagement has not been thoroughly studied.MethodsThis study aims to investigate the relationship among personality traits, emotion regulation and learning engagement. A questionnaire survey was conducted on some college students in Shandong Province, China.ResultsThe results show that: (1) there are no significant differences in Big Five Personality Traits, learning engagement, and emotion regulation by gender, grade level, and subject category to which the major belongs. (2) The personality traits of college students can directly affect learning engagement. (3) Emotion regulation partially mediates the relationship between personality traits and learning engagement.DiscussionThe study reveals the importance of personality traits and emotion regulation on students’ learning. It has a significant meaning in enhancing students’ learning engagement level.' WHERE id = 45301;

-- id=45303 source=page_meta | Enhancing Social Bonding and Well-being for the Elderly through AI-Powered Social Robots
UPDATE papers SET authors = 'Tseng, Hsiao-Ting, Lo, Chia-Lun', snippet = 'With the global challenge of aging, ensuring proper elderly care and social well-being is pivotal. This study explores the potential of AI-powered social robots in building an elderly community network based on a localized friend recommendation model. The goal is to leverage social robots to improve elderly social bonding, participation, friendship networks, and activities, thereby mitigating the risk of lonely aging. Utilizing deep learning, we analyze personality traits from the lifestyle data of the elderly. Next, machine learning generates a friend recommendation model by incorporating these traits with interests, hobbies, and local geospatial data. The recommended connections are then facilitated through interactive social robots. This study aims to bolster community engagement for the elderly, combining efficient AI analysis with practical robotic solutions tailored for their needs.' WHERE id = 45303;

-- id=45307 source=page_meta | The Influence of Personality Traits on Leadership Styles among Student Leaders in Malaysia
UPDATE papers SET authors = 'Muhammad Az Zuhri Mohd Nasir, Aini Azeqa Ma’rof, Mohd Roslan Rosnon', snippet = 'HRMARS - This study investigates the influence of personality traits on leadership styles among student leaders in Malaysian public universities. Using the Big Five Personality Traits framework, the research examines how traits like extraversion, agreeableness, conscientiousness, neuroticism, and openness shape people-oriented and task-oriented leadership. A diverse sample of 400 student leaders was analyzed through quantitative methods, including correlation and regression analyses. The results indicate that extraversion and agreeableness are strongly associated with people-oriented leadership, while conscientiousness is a significant predictor of task-oriented leadership. Neuroticism was found to negatively impact both leadership styles, suggesting emotional instability may hinder leadership effectiveness. These findings highlight the critical role of personality traits in shaping leadership behaviors and underscore the need for leadership development programs that align with individual personality profiles. This study provides valuable insights into leadership development in the multicultural context of Malaysian public universities. It also contributes to a broader understanding of how personality influences leadership, offering practical implications for designing tailored leadership programs that enhance both relational and goal-oriented leadership skills.' WHERE id = 45307;

-- id=45310 source=page_meta | A study on personality factors of school-going adolescents
UPDATE papers SET authors = 'Moumita Karmakar, Malay Halder, Shyamal Mistry, Santosh Muhkerjee, Samirranjan Adhikari', snippet = 'Personality is extremely organised and patterned body of habits, traits, attitudes and ideas of an individual. Personality factors play an important role in learning process and proper grooming of students from early childhood. In this context the study was conducted to establish the contemporary status of personality factors of school-going adolescents. In order to meet the descriptive survey method, 706 school-going adolescents were selected from Government, Government Sponsored and Government aided secondary and higher secondary schools of West Bengal to consider as sample; and data were collected by administering the Big Five Inventory (Goldberg, 1993). It was observed that the adolescents have high score in case of Extraversion, Agreeableness, Conscientiousness and Openness and have low sore in Neuroticism. As seen from Comparative Analysis the female adolescents were scored higher in Extraversion and Agreeableness; otherwise, there was no gender difference in the rest of the factors of personality.' WHERE id = 45310;

-- id=45316 source=page_meta | Personality and help-seeking for psychological distress: a systematic review and meta-anal
UPDATE papers SET authors = 'Szücs, Anna, Lam, Rachel Hui Xin, Tang, Wymann Shao Wen, Zhou, Lifan, Lazarus, Monica, Maier, Andrea B.  B, Valderas, Jose M.', snippet = 'IntroductionThe effective management of depression, anxiety, and other forms of psychological distress depends on individuals’ readiness to seek and accept help for their mental suffering. Understanding which personality traits relate to help-seeking can help better tailor mental healthcare to individual needs. However, findings regarding associations of personality traits with help-seeking have been inconsistent.MethodsThis systematic review and meta-analysis focused on English-language research studies on the association of personality (encompassing personality disorders, Five Factor –Big Five– dimensions, and other measures of personality) with depression, anxiety, or unspecified psychological distress in adults aged 18 years and older. Procedures followed the Preferred Reporting Items for Systematic Reviews and Meta-Analyses (PRISMA) guidelines. The search strategy included two concepts: personality and help-seeking and was carried out on PubMed, Embase, Web of Science, and PsycINFO. Reference tracking and searches on Google Scholar were additionally performed. Sufficiently homogeneous subsections were analyzed by meta-analysis.ResultsA total of 48 studies described in 47 records reported on the association between personality and help-seeking. Nine assessed personality disorders, 29 Five Factor dimensions, and 13 other personality constructs. Twenty-three studies investigated attitudes towards help-seeking while 25 studies investigated help-seeking behaviors. Of the studies investigating behavior, three used external observations, the rest relied on self-reports/clinician-administered questionnaires. Evidence highlighted a dissociation between attitudes and behavior for schizotypal and borderline personality disorders, and neuroticism, which displayed negative help-seeking attitudes but more help-seeking behavior. By contrast, paranoid, schizoid and obsessive-compulsive personality disorders related to both negative help-seeking attitudes and behavior across…' WHERE id = 45316;

