name = "research-emails"
main = "worker.js"
compatibility_date = "2025-01-09"

[[d1_databases]]
binding = "research"
database_name = "research"
database_id = "0ec60f00-4ffb-42c8-8006-dabe86fcd897"

[[send_email]]
name = "Research"
